// <auto-generated>
// Unity ScrollSystem - UIPlugInScrollGrid
// SSOT: skills/devian-unity/23-ui-package/35-ui-plugin-scroll-system/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// N열 그리드 섹션. Content 자식으로 Prefab에 배치한다.
    /// Inspector에서 그리드 설정을 구성하고, 런타임에 CellCount와 콜백을 설정한다.
    /// Grid 자체는 config holder이며, 셀은 Container가 BundlePool로 Content에 Spawn한다.
    /// </summary>
    public class UIPlugInScrollGrid : MonoBehaviour
    {
        // ─── Inspector Configuration ───

        [Header("Grid")]
        [SerializeField] private string _cellPrefabName;
        [SerializeField] private int _columnCount = 4;
        [SerializeField] private Vector2 _cellSize = new Vector2(200, 200);
        [SerializeField] private Vector2 _spacing = new Vector2(10, 10);

        // ─── Properties ───

        public string CellPrefabName
        {
            get => _cellPrefabName;
            set => _cellPrefabName = value;
        }

        public int ColumnCount
        {
            get => _columnCount;
            set => _columnCount = value;
        }

        public Vector2 CellSize
        {
            get => _cellSize;
            set => _cellSize = value;
        }

        public Vector2 Spacing
        {
            get => _spacing;
            set => _spacing = value;
        }

        // ─── Runtime State ───

        public int CellCount { get; private set; }

        public void SetCellCount(int count)
        {
            CellCount = count;
        }

        // ─── Callbacks ───

        /// <summary>
        /// 셀이 Spawn되어 데이터를 표시해야 할 때 호출.
        /// (셀 컴포넌트, Grid 내 local index).
        /// </summary>
        public Action<UIPlugInScrollCell, int> onBindCell;

        /// <summary>
        /// 셀이 Despawn되기 전에 호출.
        /// </summary>
        public Action<UIPlugInScrollCell> onUnbindCell;

        // ─── Internal (Container가 Init 시 설정) ───

        internal int SectionIndex;
        internal int RowCount;
        internal float TotalHeight;
        internal int FirstLayoutRowIndex;
    }
}
