// <auto-generated>
// Unity Scroll - UI_SCROLL_CELL_ID
// SSOT: skills/devian-unity/23-ui-package/21-ui-scroll-system/21-ui-scroll-cell-id/SKILL.md
// </auto-generated>

using System;

namespace Devian
{
    /// <summary>
    /// UIScrollGridCell 프리팹을 참조하기 위한 string wrapper ID.
    /// Inspector에서 UIScrollCellIdSelector를 통해 선택한다.
    /// </summary>
    [Serializable]
    public sealed class UI_SCROLL_CELL_ID
    {
        public string Value;

        public bool IsValid => !string.IsNullOrEmpty(Value);

        public static implicit operator string(UI_SCROLL_CELL_ID obj)
        {
            return obj == null ? string.Empty : (obj.Value ?? string.Empty);
        }

        public static implicit operator UI_SCROLL_CELL_ID(string value)
        {
            return new UI_SCROLL_CELL_ID { Value = value };
        }
    }
}
