// <auto-generated>
// Unity Container - UIFrameCommon
// SSOT: skills/devian-unity/23-ui-package/22-ui-container-scroll-view/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// 고정 프리팹 섹션 (배너, 헤더, 구분선 등).
    /// Logical row 1개. BindRow에서 위치 설정 + SetActive(true).
    /// </summary>
    public class UIFrameCommon : UIContainerFrameBase, IScrollSection
    {
        public Action<UIFrameCommon> onBind;
        public Action<UIFrameCommon> onUnbind;

        private static readonly Vector2 TopLeft = new Vector2(0f, 1f);
        private bool _isBound;

        // ─── IScrollSection ───

        public int GetLogicalRowCount() => 1;
        public float GetLogicalRowMainAxisSize(int localRowIndex) => GetHeight();
        public float GetLogicalRowSpacing() => 0f;

        public void ApplySectionLayout(in ScrollSectionLayout layout)
        {
            gameObject.SetActive(false);
            _isBound = false;
        }

        public void BindRow(in ScrollRowLayout rowLayout)
        {
            var rt = (RectTransform)transform;
            rt.anchorMin = TopLeft;
            rt.anchorMax = TopLeft;
            rt.pivot = TopLeft;

            if (rowLayout.Direction == ScrollDirection.Vertical)
            {
                rt.anchoredPosition = new Vector2(0, -rowLayout.RowMainAxisPosition);
                rt.sizeDelta = new Vector2(rowLayout.CrossAxisSize, rowLayout.RowMainAxisSize);
            }
            else
            {
                rt.anchoredPosition = new Vector2(rowLayout.RowMainAxisPosition, 0);
                rt.sizeDelta = new Vector2(rowLayout.RowMainAxisSize, rowLayout.CrossAxisSize);
            }

            gameObject.SetActive(true);
            _isBound = true;
            onBind?.Invoke(this);
        }

        public void UnbindRow(int localRowIndex)
        {
            if (!_isBound) return;
            onUnbind?.Invoke(this);
            gameObject.SetActive(false);
            _isBound = false;
        }

        public void RefreshRow(int localRowIndex)
        {
            if (!_isBound) return;
            onUnbind?.Invoke(this);
            onBind?.Invoke(this);
        }

        public void ClearSection()
        {
            if (_isBound)
                onUnbind?.Invoke(this);
            gameObject.SetActive(false);
            _isBound = false;
        }

        internal override void _Clear() => ClearSection();
    }
}
