// <auto-generated>
// Unity Container - UISimpleContainer
// SSOT: skills/devian-unity/23-ui-package/21-container-simple/SKILL.md
// </auto-generated>

using System.Collections.Generic;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// 최소 container 구현체.
    /// ScrollRect/가상화/레이아웃 없이 UIBaseFrame subtree만 초기화한다.
    /// Nested container는 지원하지 않는다.
    /// </summary>
    public class UISimpleContainer : UIBaseContainer
    {
        public bool IsInitialized => _initialized;

        private readonly List<UIBaseFrame> _frames = new List<UIBaseFrame>();
        private bool _initialized;

        protected override void onInitComplete()
        {
            _frames.Clear();
            _frames.AddRange(GetComponentsInChildren<UIBaseFrame>(true));

            foreach (var frame in _frames)
                frame._Init(canvas);

            foreach (var frame in _frames)
                frame._InitComplete();

            _initialized = true;
        }

        public void Clear()
        {
            foreach (var frame in _frames)
                frame._Clear();

            _frames.Clear();
            _initialized = false;
        }

        private void OnDestroy()
        {
            if (_initialized)
                Clear();
        }
    }
}
