// <auto-generated>
// Devian Build System - build.json v9 Schema
// </auto-generated>

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Devian.Tools.Models
{
    /// <summary>
    /// build.json v10 루트 스키마
    /// </summary>
    public class BuildConfig
    {
        [JsonPropertyName("version")]
        public string Version { get; set; } = "";

        [JsonPropertyName("tempDir")]
        public string TempDir { get; set; } = "temp";

        /// <summary>
        /// build.json이 위치한 디렉토리 (런타임에 설정됨)
        /// 모든 상대 경로는 이 디렉토리 기준으로 해석됨
        /// </summary>
        [JsonIgnore]
        public string ConfigDir { get; set; } = "";

        /// <summary>
        /// Data Domains (contracts + tables)
        /// </summary>
        [JsonPropertyName("domains")]
        public Dictionary<string, DomainConfig>? Domains { get; set; }

        /// <summary>
        /// Protocol Groups (배열)
        /// </summary>
        [JsonPropertyName("protocols")]
        public List<ProtocolGroupConfig>? Protocols { get; set; }
    }

    /// <summary>
    /// Data Domain 설정 (contracts + tables)
    /// </summary>
    public class DomainConfig
    {
        [JsonPropertyName("contractsDir")]
        public string ContractsDir { get; set; } = "";

        [JsonPropertyName("contractFiles")]
        public List<string> ContractFiles { get; set; } = new();

        [JsonPropertyName("tablesDir")]
        public string TablesDir { get; set; } = "";

        [JsonPropertyName("tableFiles")]
        public List<string> TableFiles { get; set; } = new();

        [JsonPropertyName("csTargetDirs")]
        public List<string> CsTargetDirs { get; set; } = new();

        [JsonPropertyName("tsTargetDirs")]
        public List<string> TsTargetDirs { get; set; } = new();

        [JsonPropertyName("upmTargetDirs")]
        public List<string> UpmTargetDirs { get; set; } = new();

        [JsonPropertyName("dataTargetDirs")]
        public List<string> DataTargetDirs { get; set; } = new();
    }

    /// <summary>
    /// Protocol Group 설정
    /// </summary>
    public class ProtocolGroupConfig
    {
        [JsonPropertyName("group")]
        public string Group { get; set; } = "";

        [JsonPropertyName("protocolDir")]
        public string ProtocolDir { get; set; } = "";

        [JsonPropertyName("protocolFiles")]
        public List<string> ProtocolFiles { get; set; } = new();

        [JsonPropertyName("csTargetDir")]
        public string CsTargetDir { get; set; } = "";

        [JsonPropertyName("tsTargetDir")]
        public string TsTargetDir { get; set; } = "";
    }
}
