// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Devian.Tools.Models
{

    /// <summary>
    /// 프로토콜 스펙 (JSON 입력)
    /// </summary>
    public class ProtocolSpec
    {
        [JsonPropertyName("namespace")]
        public string Namespace { get; set; } = "";

        [JsonPropertyName("packets")]
        public List<PacketSpec> Packets { get; set; } = new();
    }

    /// <summary>
    /// 패킷 스펙
    /// </summary>
    public class PacketSpec
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("opcode")]
        public int? Opcode { get; set; }

        [JsonPropertyName("direction")]
        public string Direction { get; set; } = "C2S"; // C2S, S2C, Bi

        [JsonPropertyName("fields")]
        public List<FieldSpec> Fields { get; set; } = new();
    }

    /// <summary>
    /// 필드 스펙
    /// </summary>
    public class FieldSpec
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("type")]
        public string Type { get; set; } = "";

        [JsonPropertyName("optional")]
        public bool Optional { get; set; }

        [JsonPropertyName("comment")]
        public string? Comment { get; set; }
    }
}
