// <auto-generated>
// Devian Unity Editor - TableID PropertyDrawer Base
// </auto-generated>

#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Base class for TableID PropertyDrawer.
    /// Derived classes should provide the selector instance.
    /// </summary>
    /// <typeparam name="TSelector">Selector type derived from BaseEditorID_Selector</typeparam>
    public abstract class BaseEditorID_Drawer<TSelector> : PropertyDrawer
        where TSelector : BaseEditorID_Selector
    {
        private const float ButtonWidth = 60f;

        /// <summary>
        /// Get or create the selector instance for this drawer.
        /// </summary>
        protected abstract TSelector GetSelector();

        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            EditorGUI.BeginProperty(position, label, property);

            // Draw label
            position = EditorGUI.PrefixLabel(position, GUIUtility.GetControlID(FocusType.Passive), label);

            // Split rect for value display and button
            var (valueRect, buttonRect) = EditorRectUtil.SplitRectFixedRight(position, ButtonWidth);

            // Get Value property
            var valueProp = property.FindPropertyRelative("Value");
            if (valueProp == null)
            {
                EditorGUI.LabelField(position, "Error: No 'Value' property found");
                EditorGUI.EndProperty();
                return;
            }

            // Display current value (read-only)
            var currentValue = GetValueDisplayString(valueProp);
            EditorGUI.LabelField(valueRect, currentValue, EditorStyles.textField);

            // Select button
            if (GUI.Button(buttonRect, "Select"))
            {
                var selector = GetSelector();
                selector.Bind(property);
                selector.Reload();
                selector.Init(currentValue);
            }

            EditorGUI.EndProperty();
        }

        /// <summary>
        /// Get display string for the current value.
        /// </summary>
        protected virtual string GetValueDisplayString(SerializedProperty valueProp)
        {
            return valueProp.propertyType switch
            {
                SerializedPropertyType.Integer => valueProp.intValue.ToString(),
                SerializedPropertyType.String => valueProp.stringValue ?? string.Empty,
                SerializedPropertyType.Enum => valueProp.enumNames[valueProp.enumValueIndex],
                _ => valueProp.ToString()
            };
        }
    }
}

#endif
