// <auto-generated>
// Unity Prefs - IntPrefs
// SSOT: skills/devian-unity/30-unity-components/24-player-prefs/SKILL.md
// </auto-generated>

using UnityEngine;

namespace Devian
{
    /// <summary>
    /// PlayerPrefs wrapper for int values.
    /// If key doesn't exist on get, stores defaultValue and returns it.
    /// </summary>
    public sealed class IntPrefs : PrefsValue<int>
    {
        public IntPrefs(string key, int defaultValue) : base(key, defaultValue) { }

        public override int Value
        {
            get
            {
                if (PlayerPrefs.HasKey(key)) return PlayerPrefs.GetInt(key);
                PlayerPrefs.SetInt(key, defaultValue);
                return defaultValue;
            }
            set => PlayerPrefs.SetInt(key, value);
        }
    }
}
