// <auto-generated>
// Unity Pool - BundlePoolFactory
// SSOT: skills/devian-upm/30-unity-components/04-pool-factories/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// AssetBundle-based pool factory.
    /// Loads prefabs via AssetManager and spawns by name.
    /// </summary>
    public sealed class BundlePoolFactory : IPoolFactory
    {
        /// <inheritdoc/>
        public GameObject GetPrefab(string name)
        {
            // Use AssetManager static API (not Instance pattern)
            return AssetManager.GetAsset<GameObject>(name);
        }
        
        /// <inheritdoc/>
        public Type GetPoolType(GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));
            
            var components = prefab.GetComponents<Component>();
            var iPoolableGenericDef = typeof(IPoolable<>);
            
            foreach (var component in components)
            {
                if (component == null) continue;
                
                var componentType = component.GetType();
                var interfaces = componentType.GetInterfaces();
                
                foreach (var iface in interfaces)
                {
                    if (iface.IsGenericType && iface.GetGenericTypeDefinition() == iPoolableGenericDef)
                    {
                        return componentType;
                    }
                }
            }
            
            throw new InvalidOperationException(
                $"Prefab '{prefab.name}' does not have a component implementing IPoolable<>.");
        }
        
        /// <inheritdoc/>
        public Component CreateInstance(GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));
            
            var go = UnityEngine.Object.Instantiate(prefab);
            var poolType = GetPoolType(prefab);
            return go.GetComponent(poolType);
        }
        
        /// <inheritdoc/>
        public void DestroyInstance(Component instance)
        {
            if (instance == null) return;
            
#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                UnityEngine.Object.DestroyImmediate(instance.gameObject);
                return;
            }
#endif
            UnityEngine.Object.Destroy(instance.gameObject);
        }
    }
}
