// <auto-generated>
// Unity Singleton - AutoSingleton<T>
// SSOT: skills/devian-upm/30-unity-components/01-singleton/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Auto-create singleton - creates instance on first access.
    /// Uses Find-first strategy: searches scene before creating new.
    /// Main thread required for auto-creation.
    /// </summary>
    /// <typeparam name="T">Concrete singleton type</typeparam>
    public abstract class AutoSingleton<T> : MonoBehaviour where T : AutoSingleton<T>
    {
        private static T _instance;
        private static readonly object _lock = new object();
        private static bool _isQuitting = false;
        
        /// <summary>
        /// Returns true if an instance exists.
        /// </summary>
        public static bool HasInstance => _instance != null;
        
        /// <summary>
        /// Gets the singleton instance. Creates if not exists (main thread only).
        /// Throws InvalidOperationException during application quit or from non-main thread.
        /// </summary>
        public static T Instance
        {
            get
            {
                // Fast path: instance exists
                if (_instance != null)
                    return _instance;
                
                lock (_lock)
                {
                    // Double-check after lock
                    if (_instance != null)
                        return _instance;
                    
                    // Quit check
                    if (_isQuitting)
                    {
                        throw new InvalidOperationException(
                            $"[{typeof(T).Name}] Cannot access singleton during application quit.");
                    }
                    
                    // Main thread check (required for Find/Create)
                    UnityMainThread.EnsureOrThrow($"{typeof(T).Name}.Instance");
                    
                    // Step 1: Find existing in scene (including inactive)
#if UNITY_2023_1_OR_NEWER
                    _instance = FindAnyObjectByType<T>(FindObjectsInactive.Include);
#else
                    _instance = FindObjectOfType<T>(true);
#endif
                    
                    if (_instance != null)
                    {
                        DontDestroyOnLoad(_instance.gameObject);
                        return _instance;
                    }
                    
                    // Step 2: Create new
                    var go = new GameObject($"[{typeof(T).Name}]");
                    _instance = go.AddComponent<T>();
                    DontDestroyOnLoad(go);
                    
                    return _instance;
                }
            }
        }
        
        /// <summary>
        /// Called by Unity. Handles duplicate detection.
        /// </summary>
        protected virtual void Awake()
        {
            lock (_lock)
            {
                if (_instance != null && _instance != this)
                {
                    Debug.LogWarning($"[{typeof(T).Name}] Duplicate instance detected. Destroying this.");
                    UnityEngine.Object.Destroy(gameObject);
                    return;
                }
                
                _instance = (T)this;
                DontDestroyOnLoad(gameObject);
            }
        }
        
        /// <summary>
        /// Called by Unity. Sets quit flag to prevent recreation.
        /// </summary>
        protected virtual void OnApplicationQuit()
        {
            _isQuitting = true;
        }
        
        /// <summary>
        /// Called by Unity. Clears instance reference if this is the registered instance.
        /// </summary>
        protected virtual void OnDestroy()
        {
            lock (_lock)
            {
                if (_instance == this)
                {
                    _instance = null;
                }
            }
        }
    }
}
