// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System v10
// </auto-generated>

import * as C2SampleMod from './C2Sample.g';
import * as Sample2CMod from './Sample2C.g';
import * as ServerRuntimeMod from './generated/ServerRuntime.g';
import * as ClientRuntimeMod from './generated/ClientRuntime.g';

export { C2Sample } from './C2Sample.g';
export { Sample2C } from './Sample2C.g';
export * as ServerRuntime from './generated/ServerRuntime.g';
export * as ClientRuntime from './generated/ClientRuntime.g';

export { createServerRuntime } from './generated/ServerRuntime.g';
export { createClientRuntime } from './generated/ClientRuntime.g';

// Devian namespace tree - defined only in index.ts
export namespace Devian {
    export namespace Network {
        export namespace Sample {
            export import C2Sample = C2SampleMod.C2Sample;
            export import Sample2C = Sample2CMod.Sample2C;
            export import ServerRuntime = ServerRuntimeMod;
            export import ClientRuntime = ClientRuntimeMod;
        }
    }
}
