// <auto-generated>
// Unity UIPackage - UI_CANVAS_ID
// SSOT: skills/devian-unity/23-ui-package/12-ui-canvas-id/SKILL.md
// </auto-generated>

using System;

namespace Devian
{
    /// <summary>
    /// UICanvas 프리팹을 참조하기 위한 string wrapper ID.
    /// Inspector에서 UICanvasIdSelector를 통해 선택한다.
    /// </summary>
    [Serializable]
    public sealed class UI_CANVAS_ID
    {
        public string Value;

        public bool IsValid => !string.IsNullOrEmpty(Value);

        public static implicit operator string(UI_CANVAS_ID obj)
        {
            return obj == null ? string.Empty : (obj.Value ?? string.Empty);
        }

        public static implicit operator UI_CANVAS_ID(string value)
        {
            return new UI_CANVAS_ID
            {
                Value = value
            };
        }
    }
}
