// <auto-generated>
// Unity Pool - IPoolFactory Interface
// SSOT: skills/devian-common-upm/30-unity-components/02-pool-manager/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Factory interface for creating and managing pooled instances.
    /// Implement this to provide different prefab loading strategies.
    /// </summary>
    public interface IPoolFactory
    {
        /// <summary>
        /// Gets the prefab by name.
        /// </summary>
        /// <param name="name">The prefab name (typically gameObject.name)</param>
        /// <returns>The prefab GameObject, or null if not found</returns>
        GameObject GetPrefab(string name);
        
        /// <summary>
        /// Gets the pool type from a prefab.
        /// Should find the IPoolable&lt;&gt; component and return its type.
        /// </summary>
        /// <param name="prefab">The prefab to inspect</param>
        /// <returns>The Component type that implements IPoolable&lt;&gt;</returns>
        Type GetPoolType(GameObject prefab);
        
        /// <summary>
        /// Creates a new instance from the prefab.
        /// Typically calls Instantiate internally.
        /// </summary>
        /// <param name="prefab">The prefab to instantiate</param>
        /// <returns>The poolable component on the new instance</returns>
        Component CreateInstance(GameObject prefab);
        
        /// <summary>
        /// Destroys an instance.
        /// Typically calls Destroy internally.
        /// </summary>
        /// <param name="instance">The instance to destroy</param>
        void DestroyInstance(Component instance);
    }
}
