// <auto-generated>
// Unity Pool - InspectorPoolFactory
// SSOT: skills/devian-unity/30-unity-components/04-pool-factories/SKILL.md
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Inspector-based pool factory.
    /// Register prefabs via the Inspector and spawn by name.
    /// </summary>
    public sealed class InspectorPoolFactory : MonoBehaviour, IPoolFactory
    {
        [SerializeField]
        private GameObject[] _prefabs = Array.Empty<GameObject>();
        
        private Dictionary<string, GameObject> _prefabByName = new Dictionary<string, GameObject>();
        
        private void Awake()
        {
            RebuildCache();
        }
        
        private void OnEnable()
        {
            RebuildCache();
        }
        
#if UNITY_EDITOR
        private void OnValidate()
        {
            RebuildCache();
        }
#endif
        
        private void RebuildCache()
        {
            _prefabByName.Clear();
            if (_prefabs == null) return;
            
            foreach (var prefab in _prefabs)
            {
                if (prefab == null) continue;
                _prefabByName[prefab.name] = prefab;
            }
        }
        
        /// <inheritdoc/>
        public GameObject GetPrefab(string name)
        {
            return _prefabByName.TryGetValue(name, out var prefab) ? prefab : null;
        }
        
        /// <inheritdoc/>
        public Type GetPoolType(GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));
            
            var components = prefab.GetComponents<Component>();
            var iPoolableGenericDef = typeof(IPoolable<>);
            
            foreach (var component in components)
            {
                if (component == null) continue;
                
                var componentType = component.GetType();
                var interfaces = componentType.GetInterfaces();
                
                foreach (var iface in interfaces)
                {
                    if (iface.IsGenericType && iface.GetGenericTypeDefinition() == iPoolableGenericDef)
                    {
                        return componentType;
                    }
                }
            }
            
            throw new InvalidOperationException(
                $"Prefab '{prefab.name}' does not have a component implementing IPoolable<>.");
        }
        
        /// <inheritdoc/>
        public Component CreateInstance(GameObject prefab)
        {
            if (prefab == null)
                throw new ArgumentNullException(nameof(prefab));
            
            var go = UnityEngine.Object.Instantiate(prefab);
            var poolType = GetPoolType(prefab);
            return go.GetComponent(poolType);
        }
        
        /// <inheritdoc/>
        public void DestroyInstance(Component instance)
        {
            if (instance == null) return;
            
#if UNITY_EDITOR
            if (!Application.isPlaying)
            {
                UnityEngine.Object.DestroyImmediate(instance.gameObject);
                return;
            }
#endif
            UnityEngine.Object.Destroy(instance.gameObject);
        }
    }
}
