// <auto-generated>
// Unity Pool - IPoolFactory Extension Methods
// SSOT: skills/devian-unity/30-unity-components/02-pool-manager/SKILL.md
// </auto-generated>

using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Extension methods for IPoolFactory providing convenient Spawn/Despawn API.
    /// This is the primary user-facing API for object pooling.
    ///
    /// Usage:
    ///   var enemy = myFactory.Spawn&lt;Enemy&gt;("Goblin", position, rotation);
    ///   myFactory.Despawn(enemy);
    ///
    /// Debug Hierarchy:
    ///   [PoolManager]/{TypeName}/{PoolName}/Inactive
    /// </summary>
    public static class PoolFactoryExtensions
    {
        /// <summary>
        /// Spawns a pooled instance by prefab name using this factory.
        /// Creates or reuses a Pool for the given (factory, type, poolName) combination.
        ///
        /// Parent policy:
        /// - If parent is null, instance goes under [PoolManager]/{Type}/{Name}
        /// - If parent is provided, instance goes under that parent (game logic priority)
        /// </summary>
        /// <typeparam name="T">The poolable component type</typeparam>
        /// <param name="factory">The factory to use for prefab lookup and instance creation</param>
        /// <param name="name">Prefab name to spawn (also used as pool name for hierarchy)</param>
        /// <param name="position">World position (default: Vector3.zero)</param>
        /// <param name="rotation">Rotation (default: Quaternion.identity)</param>
        /// <param name="parent">Optional parent transform (if null, uses debug hierarchy)</param>
        /// <param name="options">Pool options (MaxSize, etc.)</param>
        /// <returns>The spawned instance</returns>
        public static T Spawn<T>(
            this IPoolFactory factory,
            string name,
            Vector3 position = default,
            Quaternion rotation = default,
            Transform parent = null,
            PoolOptions options = default) where T : Component, IPoolable<T>
        {
            UnityMainThread.EnsureOrThrow("IPoolFactory.Spawn");
            
            // Get or create pool for this (factory, type, poolName) combination
            var pool = PoolManager.Instance._GetOrCreatePool<T>(factory, name, options);
            
            // Spawn from the pool
            return pool.Spawn(name, position, rotation, parent) as T;
        }
        
        /// <summary>
        /// Despawns an instance back to its pool.
        /// Instance is always moved under [PoolManager]/{Type}/{Name}/Inactive.
        /// The factory parameter is for API consistency; routing uses PoolTag.
        /// </summary>
        /// <param name="factory">The factory (unused, routing is PoolTag-based)</param>
        /// <param name="instance">The instance to despawn</param>
        public static void Despawn(this IPoolFactory factory, Component instance)
        {
            UnityMainThread.EnsureOrThrow("IPoolFactory.Despawn");
            
            // Delegate to PoolManager (PoolTag-based routing)
            PoolManager.Instance.Despawn(instance);
        }
    }
}
