#!/usr/bin/env node
// <auto-generated>
// Devian Build System v10 - Node.js Build Runner
// SSOT: skills/devian/03-ssot/SKILL.md
// </auto-generated>

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Generators
import { generateCSharpProtocol } from './generators/protocol-cs.js';
import { generateTypeScriptProtocol, generateServerRuntime, generateClientRuntime } from './generators/protocol-ts.js';
import { generateCSharpContract, generateCSharpContractBody } from './generators/contract-cs.js';
import { generateTypeScriptContract, generateTypeScriptContractBody } from './generators/contract-ts.js';
import { generateCSharpTable, generateCSharpTableEntityBody, generateCSharpTableContainerBody, generateTypeScriptTable, generateTypeScriptTableBody, generateTypeScriptTableContainerBody, generateTableData, parseXlsx, collectEnumGenSpecs, generateCSharpEnums, generateTypeScriptEnums } from './generators/table.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================================================
// Build Runner
// ============================================================================

class DevianToolBuilder {
    constructor(buildJsonPath) {
        this.buildJsonPath = path.resolve(buildJsonPath);
        // input/build.json -> input (buildJsonDir) -> devian (rootDir)
        // All relative paths in build.json are relative to buildJsonDir
        this.buildJsonDir = path.dirname(this.buildJsonPath);
        this.rootDir = path.dirname(this.buildJsonDir);
        this.config = null;
        this.tempDir = null;
    }

    // Resolve path relative to buildJsonDir
    resolvePath(relativePath) {
        if (path.isAbsolute(relativePath)) {
            return relativePath;
        }
        return path.resolve(this.buildJsonDir, relativePath);
    }

    async run() {
        console.log('='.repeat(60));
        console.log('Devian Build System v10');
        console.log('='.repeat(60));
        console.log(`Build config: ${this.buildJsonPath}`);
        console.log(`Root dir: ${this.rootDir}`);
        console.log();

        // 1. Load config
        this.config = JSON.parse(fs.readFileSync(this.buildJsonPath, 'utf-8'));
        // tempDir is relative to build.json directory
        this.tempDir = path.join(this.buildJsonDir, this.config.tempDir || 'temp');

        // 1.5. Forbidden namespace guard (재발 방지)
        console.log('[Guard] Checking forbidden namespaces...');
        this.checkForbiddenNamespaces();

        // 2. Clean temp dir
        console.log('[Phase 0] Cleaning temp directory...');
        if (fs.existsSync(this.tempDir)) {
            fs.rmSync(this.tempDir, { recursive: true });
        }
        fs.mkdirSync(this.tempDir, { recursive: true });

        // 3. Generate to staging
        console.log('[Phase 1] Generating to staging...');
        
        // Process domains (contracts + tables)
        if (this.config.domains) {
            for (const [domainName, domainConfig] of Object.entries(this.config.domains)) {
                await this.processDomain(domainName, domainConfig);
            }
        }

        // Process protocols
        if (this.config.protocols && Array.isArray(this.config.protocols)) {
            for (const protocolGroup of this.config.protocols) {
                await this.processProtocolGroup(protocolGroup);
            }
        }

        // Process static UPM packages (e.g., com.devian.unity.common)
        if (this.config.staticUpmPackages && Array.isArray(this.config.staticUpmPackages)) {
            for (const pkgConfig of this.config.staticUpmPackages) {
                await this.processStaticUpmPackage(pkgConfig);
            }
        }

        // 4. Clean & Copy to targets
        console.log('[Phase 2] Clean & Copy to targets...');
        
        if (this.config.domains) {
            for (const [domainName, domainConfig] of Object.entries(this.config.domains)) {
                await this.copyDomainToTargets(domainName, domainConfig);
            }
        }

        if (this.config.protocols && Array.isArray(this.config.protocols)) {
            for (const protocolGroup of this.config.protocols) {
                await this.copyProtocolGroupToTargets(protocolGroup);
            }
        }

        if (this.config.staticUpmPackages && Array.isArray(this.config.staticUpmPackages)) {
            for (const pkgConfig of this.config.staticUpmPackages) {
                await this.copyStaticUpmPackageToTarget(pkgConfig);
            }
        }

        // 5. Sync UPM samples metadata
        console.log('[Phase 3] Sync UPM samples metadata...');
        await this.syncAllUpmSamples();

        console.log();
        console.log('='.repeat(60));
        console.log('Build completed successfully!');
        console.log('='.repeat(60));
    }

    // ========================================================================
    // Domain Processing (Contracts + Tables)
    // ========================================================================

    async processDomain(domainName, config) {
        console.log(`  [Domain] ${domainName}`);

        const stagingCs = path.join(this.tempDir, domainName, 'cs', 'generated');
        const stagingTs = path.join(this.tempDir, domainName, 'ts', 'generated');
        const stagingTsRoot = path.join(this.tempDir, domainName, 'ts');
        const stagingData = path.join(this.tempDir, domainName, 'data', 'json');

        fs.mkdirSync(stagingCs, { recursive: true });
        fs.mkdirSync(stagingTs, { recursive: true });
        fs.mkdirSync(stagingData, { recursive: true });

        // Collect all data for unified file generation
        const contractSpecs = [];
        const tables = [];

        // Load contracts
        if (config.contractsDir && config.contractFiles) {
            const contractsDir = this.resolvePath(config.contractsDir);
            const files = this.globFiles(contractsDir, config.contractFiles);

            for (const file of files) {
                console.log(`    [Contract] ${path.basename(file)}`);
                const spec = JSON.parse(fs.readFileSync(file, 'utf-8'));
                contractSpecs.push(spec);
            }
        }

        // Load tables
        if (config.tablesDir && config.tableFiles) {
            const tablesDir = this.resolvePath(config.tablesDir);
            const files = this.globFiles(tablesDir, config.tableFiles);

            for (const file of files) {
                console.log(`    [Table] ${path.basename(file)}`);
                const parsedTables = parseXlsx(file);
                tables.push(...parsedTables);

                // Generate NDJSON data (still individual files)
                for (const table of parsedTables) {
                    const ndjson = generateTableData(table);
                    const dataFileName = `${table.name}.ndjson`;
                    fs.writeFileSync(path.join(stagingData, dataFileName), ndjson);
                }
            }
        }

        // Generate unified C# file: {DomainName}.g.cs
        const csCode = this.generateUnifiedCSharp(domainName, contractSpecs, tables);
        fs.writeFileSync(path.join(stagingCs, `${domainName}.g.cs`), csCode);

        // Generate unified TS file: {DomainName}.g.ts
        const tsCode = this.generateUnifiedTypeScript(domainName, contractSpecs, tables);
        fs.writeFileSync(path.join(stagingTs, `${domainName}.g.ts`), tsCode);

        // Generate index.ts for TypeScript
        const indexTsContent = this.generateDomainIndexTs([domainName]);
        fs.writeFileSync(path.join(stagingTsRoot, 'index.ts'), indexTsContent);

        // Generate UPM scaffold if upmTargetDir is configured
        if (config.upmTargetDir) {
            this.generateDomainUpmScaffold(domainName, stagingCs);
        }
    }

    generateUnifiedCSharp(domainName, contractSpecs, tables) {
        const lines = [];

        // Collect enum specs from tables
        const enumSpecs = collectEnumGenSpecs(tables);

        // Header
        lines.push('// <auto-generated>');
        lines.push('// DO NOT EDIT - Generated by Devian Build System v10');
        lines.push('// </auto-generated>');
        lines.push('');
        lines.push('#nullable enable');
        lines.push('');
        lines.push('using System;');
        lines.push('using System.Collections.Generic;');
        lines.push('using System.IO;');
        lines.push('using Newtonsoft.Json;');
        lines.push('using Devian.Core;');
        lines.push('');

        // Namespace
        lines.push(`namespace Devian.Module.${domainName}`);
        lines.push('{');

        // Enums section (gen: tables only)
        if (enumSpecs.length > 0) {
            const enumCode = generateCSharpEnums(enumSpecs);
            lines.push(enumCode);
        }

        // Contracts section
        if (contractSpecs.length > 0) {
            lines.push('    // ================================================================');
            lines.push('    // Contracts');
            lines.push('    // ================================================================');
            lines.push('');

            for (const spec of contractSpecs) {
                const body = generateCSharpContractBody(spec, domainName);
                lines.push(body);
                lines.push('');
            }
        }

        // Table Entities section
        if (tables.length > 0) {
            lines.push('    // ================================================================');
            lines.push('    // Table Entities');
            lines.push('    // ================================================================');
            lines.push('');

            for (const table of tables) {
                const body = generateCSharpTableEntityBody(table);
                lines.push(body);
                lines.push('');
            }

            // Table Containers section
            lines.push('    // ================================================================');
            lines.push('    // Table Containers');
            lines.push('    // ================================================================');
            lines.push('');

            for (const table of tables) {
                const body = generateCSharpTableContainerBody(table, enumSpecs);
                lines.push(body);
                lines.push('');
            }
        }

        lines.push('}'); // end namespace

        return lines.join('\n');
    }

    generateUnifiedTypeScript(domainName, contractSpecs, tables) {
        const lines = [];

        // Collect enum specs from tables
        const enumSpecs = collectEnumGenSpecs(tables);

        // Header
        lines.push('// <auto-generated>');
        lines.push('// DO NOT EDIT - Generated by Devian Build System v10');
        lines.push('// </auto-generated>');
        lines.push('');

        // Check if we need IEntity/IEntityKey import
        const hasContractClasses = contractSpecs.some(spec => (spec.classes || []).length > 0);
        const hasTables = tables.length > 0;
        const hasKeyedTables = tables.some(t => t.keyField);

        if (hasContractClasses || hasTables) {
            const imports = ['IEntity'];
            if (hasKeyedTables) {
                imports.push('IEntityKey');
            }
            lines.push(`import { ${imports.join(', ')} } from '@devian/core';`);
            lines.push('');
        }

        // Enums section (gen: tables only)
        if (enumSpecs.length > 0) {
            const enumCode = generateTypeScriptEnums(enumSpecs);
            lines.push(enumCode);
        }

        // Contracts section
        if (contractSpecs.length > 0) {
            lines.push('// ================================================================');
            lines.push('// Contracts');
            lines.push('// ================================================================');
            lines.push('');

            for (const spec of contractSpecs) {
                const body = generateTypeScriptContractBody(spec);
                lines.push(body);
                lines.push('');
            }
        }

        // Table Interfaces section
        if (tables.length > 0) {
            lines.push('// ================================================================');
            lines.push('// Tables');
            lines.push('// ================================================================');
            lines.push('');

            for (const table of tables) {
                const body = generateTypeScriptTableBody(table);
                lines.push(body);
                lines.push('');
            }

            // Table Containers section
            lines.push('// ================================================================');
            lines.push('// Table Containers');
            lines.push('// ================================================================');
            lines.push('');

            for (const table of tables) {
                const body = generateTypeScriptTableContainerBody(table, enumSpecs);
                lines.push(body);
                lines.push('');
            }
        }

        return lines.join('\n').trimEnd();
    }

    async copyDomainToTargets(domainName, config) {
        const stagingCs = path.join(this.tempDir, domainName, 'cs', 'generated');
        const stagingTs = path.join(this.tempDir, domainName, 'ts', 'generated');
        const stagingTsRoot = path.join(this.tempDir, domainName, 'ts');
        const stagingData = path.join(this.tempDir, domainName, 'data', 'json');

        // Copy to CS target: {csTargetDir}/Devian.Module.{Domain}/generated/
        if (config.csTargetDir) {
            const csModuleName = `Devian.Module.${domainName}`;
            const resolvedTargetDir = path.join(this.resolvePath(config.csTargetDir), csModuleName);
            const target = path.join(resolvedTargetDir, 'generated');
            this.cleanAndCopy(stagingCs, target);
            console.log(`    [Copy] ${stagingCs} -> ${target}`);

            // Generate .csproj if not exists
            this.ensureCsProj(resolvedTargetDir, csModuleName);
        }

        // Copy to TS target: {tsTargetDir}/devian-module-{domain}/generated/
        if (config.tsTargetDir) {
            const tsModuleName = `devian-module-${domainName.toLowerCase()}`;
            const resolvedTargetDir = path.join(this.resolvePath(config.tsTargetDir), tsModuleName);
            const target = path.join(resolvedTargetDir, 'generated');
            this.cleanAndCopy(stagingTs, target);
            console.log(`    [Copy] ${stagingTs} -> ${target}`);

            // Update index.ts with marker-based approach (DO NOT overwrite entirely)
            this.updateDomainIndexTs(resolvedTargetDir, domainName);

            // Update features/index.ts with auto-scanned exports
            this.updateFeaturesIndexTs(resolvedTargetDir);

            // Generate tsconfig.json if not exists
            this.ensureTsConfig(resolvedTargetDir);

            // Generate package.json if not exists
            this.ensureModulePackageJson(resolvedTargetDir, tsModuleName, domainName);
        }

        // Copy to Data target: {dataTargetDir}/{Domain}/json/
        if (config.dataTargetDir) {
            const target = path.join(this.resolvePath(config.dataTargetDir), domainName, 'json');
            this.cleanAndCopy(stagingData, target);
            console.log(`    [Copy] ${stagingData} -> ${target}`);
        }

        // Copy to UPM target: {upmTargetDir}/com.devian.module.{domain}/
        if (config.upmTargetDir) {
            const stagingUpm = path.join(this.tempDir, domainName, 'upm');
            const packageName = `com.devian.module.${domainName.toLowerCase()}`;
            const target = path.join(this.resolvePath(config.upmTargetDir), packageName);
            this.copyUpmToTarget(stagingUpm, target);
            console.log(`    [Copy UPM] ${stagingUpm} -> ${target}`);
        }
    }

    // ========================================================================
    // Protocol Processing
    // ========================================================================

    async processProtocolGroup(groupConfig) {
        const groupName = groupConfig.group;
        console.log(`  [ProtocolGroup] ${groupName}`);

        const protocolDir = this.resolvePath(groupConfig.protocolDir);
        const csProjectName = `Devian.Network.${groupName}`;
        
        // Staging paths
        const stagingCs = path.join(this.tempDir, csProjectName);
        const stagingTs = path.join(this.tempDir, groupName);
        const stagingTsGenerated = path.join(stagingTs, 'generated');

        fs.mkdirSync(stagingCs, { recursive: true });
        fs.mkdirSync(stagingTs, { recursive: true });
        fs.mkdirSync(stagingTsGenerated, { recursive: true });

        // Collect protocol info for index.ts and ServerRuntime
        const protocolNames = [];
        const protocolInfos = []; // {name, direction}

        // Process each protocol file
        for (const protocolFileName of groupConfig.protocolFiles) {
            const protocolFile = path.join(protocolDir, protocolFileName);
            const protocolName = path.basename(protocolFileName, '.json');
            
            if (!fs.existsSync(protocolFile)) {
                console.error(`    Protocol file not found: ${protocolFile}`);
                continue;
            }

            console.log(`    [Protocol] ${protocolName}`);
            protocolNames.push(protocolName);

            // Load protocol spec
            const spec = JSON.parse(fs.readFileSync(protocolFile, 'utf-8'));

            // Collect protocol info for ServerRuntime
            protocolInfos.push({
                name: protocolName,
                direction: spec.direction || 'bidirectional'
            });

            // Load or create opcode registry
            const opcodeRegistry = this.loadOrCreateRegistry(protocolDir, protocolName, 'opcodes');
            const tagRegistry = this.loadOrCreateRegistry(protocolDir, protocolName, 'tags');

            // Assign opcodes and tags
            this.assignOpcodes(spec, opcodeRegistry);
            this.assignTags(spec, tagRegistry);

            // Save registries
            this.saveRegistry(protocolDir, protocolName, 'opcodes', opcodeRegistry);
            this.saveRegistry(protocolDir, protocolName, 'tags', tagRegistry);

            // C# Protocol
            const csCode = generateCSharpProtocol(spec, protocolName, groupName);
            fs.writeFileSync(path.join(stagingCs, `${protocolName}.g.cs`), csCode);

            // TypeScript Protocol
            const tsCode = generateTypeScriptProtocol(spec, protocolName, groupName);
            fs.writeFileSync(path.join(stagingTs, `${protocolName}.g.ts`), tsCode);
        }

        // Generate .csproj for C#
        const csprojContent = this.generateCsproj(groupName);
        fs.writeFileSync(path.join(stagingCs, `${csProjectName}.csproj`), csprojContent);

        // Generate ServerRuntime.g.ts for TypeScript (if both inbound/outbound exist)
        const serverRuntimeCode = generateServerRuntime(groupName, protocolInfos);
        const hasServerRuntime = serverRuntimeCode !== null;
        if (hasServerRuntime) {
            fs.writeFileSync(path.join(stagingTsGenerated, 'ServerRuntime.g.ts'), serverRuntimeCode);
            console.log(`    [ServerRuntime] generated/ServerRuntime.g.ts`);
        }

        // Generate ClientRuntime.g.ts for TypeScript (if both inbound/outbound exist)
        const clientRuntimeCode = generateClientRuntime(groupName, protocolInfos);
        const hasClientRuntime = clientRuntimeCode !== null;
        if (hasClientRuntime) {
            fs.writeFileSync(path.join(stagingTsGenerated, 'ClientRuntime.g.ts'), clientRuntimeCode);
            console.log(`    [ClientRuntime] generated/ClientRuntime.g.ts`);
        }

        // Generate index.ts for TypeScript
        const indexTsContent = this.generateIndexTs(groupName, protocolNames, hasServerRuntime, hasClientRuntime);
        fs.writeFileSync(path.join(stagingTs, 'index.ts'), indexTsContent);

        // Generate UPM scaffold if upmTargetDir is configured
        if (groupConfig.upmTargetDir) {
            this.generateProtocolUpmScaffold(groupName, stagingCs);
        }
    }

    generateCsproj(groupName) {
        return `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Devian.Network.${groupName}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Devian.Core\\Devian.Core.csproj" />
    <ProjectReference Include="..\\Devian.Network\\Devian.Network.csproj" />
    <ProjectReference Include="..\\Devian.Module.Common\\Devian.Module.Common.csproj" />
  </ItemGroup>
</Project>
`;
    }

    generateIndexTs(groupName, protocolNames, hasServerRuntime = false, hasClientRuntime = false) {
        const lines = [];

        // Header
        lines.push('// <auto-generated>');
        lines.push('// DO NOT EDIT - Generated by Devian Build System v10');
        lines.push('// </auto-generated>');
        lines.push('');

        // Import modules
        for (const name of protocolNames) {
            lines.push(`import * as ${name}Mod from './${name}.g';`);
        }
        if (hasServerRuntime) {
            lines.push(`import * as ServerRuntimeMod from './generated/ServerRuntime.g';`);
        }
        if (hasClientRuntime) {
            lines.push(`import * as ClientRuntimeMod from './generated/ClientRuntime.g';`);
        }
        lines.push('');

        // Direct exports (for convenience)
        for (const name of protocolNames) {
            lines.push(`export const ${name} = ${name}Mod.${name};`);
        }
        if (hasServerRuntime) {
            lines.push(`export const ServerRuntime = ServerRuntimeMod;`);
        }
        if (hasClientRuntime) {
            lines.push(`export const ClientRuntime = ClientRuntimeMod;`);
        }
        lines.push('');

        // Re-export factory functions for direct import
        if (hasServerRuntime) {
            lines.push(`export { createServerRuntime } from './generated/ServerRuntime.g';`);
        }
        if (hasClientRuntime) {
            lines.push(`export { createClientRuntime } from './generated/ClientRuntime.g';`);
        }
        if (hasServerRuntime || hasClientRuntime) {
            lines.push('');
        }

        // Devian namespace tree (defined only here, not in .g.ts files)
        lines.push('// Devian namespace tree - defined only in index.ts');
        lines.push('export namespace Devian {');
        lines.push('    export namespace Network {');
        lines.push(`        export namespace ${groupName} {`);
        for (const name of protocolNames) {
            lines.push(`            export import ${name} = ${name}Mod.${name};`);
        }
        if (hasServerRuntime) {
            lines.push(`            export import ServerRuntime = ServerRuntimeMod;`);
        }
        if (hasClientRuntime) {
            lines.push(`            export import ClientRuntime = ClientRuntimeMod;`);
        }
        lines.push('        }');
        lines.push('    }');
        lines.push('}');
        lines.push('');

        return lines.join('\n');
    }

    generateDomainIndexTs(fileNames) {
        const header = [
            '// <auto-generated>',
            '// DO NOT EDIT - Generated by Devian Build System v10',
            '// </auto-generated>',
            ''
        ];
        const exports = fileNames.map(name => `export * from './generated/${name}.g';`);
        return header.concat(exports).join('\n') + '\n';
    }

    async copyProtocolGroupToTargets(groupConfig) {
        const groupName = groupConfig.group;
        const csProjectName = `Devian.Network.${groupName}`;
        
        const stagingCs = path.join(this.tempDir, csProjectName);
        const stagingTs = path.join(this.tempDir, groupName);

        // Check if ServerRuntime and ClientRuntime were generated
        const hasServerRuntime = fs.existsSync(path.join(stagingTs, 'generated', 'ServerRuntime.g.ts'));
        const hasClientRuntime = fs.existsSync(path.join(stagingTs, 'generated', 'ClientRuntime.g.ts'));

        // Copy to CS target: {csTargetDir}/Devian.Network.{ProtocolGroup}/
        if (groupConfig.csTargetDir) {
            const target = path.join(this.resolvePath(groupConfig.csTargetDir), csProjectName);
            this.cleanAndCopy(stagingCs, target);
            console.log(`    [Copy] ${stagingCs} -> ${target}`);
        }

        // Copy to TS target: {tsTargetDir}/devian-network-{group}/
        if (groupConfig.tsTargetDir) {
            const tsModuleName = `devian-network-${groupName.toLowerCase()}`;
            const target = path.join(this.resolvePath(groupConfig.tsTargetDir), tsModuleName);
            this.cleanAndCopy(stagingTs, target);
            console.log(`    [Copy] ${stagingTs} -> ${target}`);

            // Generate tsconfig.json if not exists
            this.ensureTsConfig(target);

            // Generate/update package.json with correct dependencies
            this.ensureProtocolPackageJson(target, groupName, hasServerRuntime, hasClientRuntime);
        }

        // Copy to UPM target
        if (groupConfig.upmTargetDir) {
            const stagingUpm = path.join(this.tempDir, `${csProjectName}-upm`);
            const target = this.resolvePath(groupConfig.upmTargetDir);
            this.copyUpmToTarget(stagingUpm, target);
            console.log(`    [Copy UPM] ${stagingUpm} -> ${target}`);
        }
    }

    // ========================================================================
    // Opcode/Tag Registry Management
    // ========================================================================

    loadOrCreateRegistry(protocolsDir, protocolName, type) {
        const generatedDir = path.join(protocolsDir, 'generated');
        const registryPath = path.join(generatedDir, `${protocolName}.${type}.json`);
        if (fs.existsSync(registryPath)) {
            return JSON.parse(fs.readFileSync(registryPath, 'utf-8'));
        }
        return {};
    }

    saveRegistry(protocolsDir, protocolName, type, registry) {
        const generatedDir = path.join(protocolsDir, 'generated');
        fs.mkdirSync(generatedDir, { recursive: true });
        const registryPath = path.join(generatedDir, `${protocolName}.${type}.json`);
        
        // Deterministic save: sort keys (ordinal) + trailing newline
        const sortedKeys = Object.keys(registry).sort((a, b) => a.localeCompare(b));
        const sorted = {};
        for (const key of sortedKeys) {
            sorted[key] = registry[key];
        }
        fs.writeFileSync(registryPath, JSON.stringify(sorted, null, 2) + '\n');
    }

    assignOpcodes(spec, registry) {
        const MIN_OPCODE = 1000;
        const usedOpcodes = new Set();

        // Phase 1: Apply explicit opcodes from spec (highest priority)
        for (const msg of spec.messages) {
            if (msg.opcode !== undefined) {
                if (msg.opcode < 0) {
                    throw new Error(`Negative opcode not allowed: ${msg.name} = ${msg.opcode}`);
                }
                if (usedOpcodes.has(msg.opcode)) {
                    throw new Error(`Duplicate opcode: ${msg.opcode} for ${msg.name}`);
                }
                usedOpcodes.add(msg.opcode);
                registry[msg.name] = msg.opcode;
            }
        }

        // Phase 2: Apply registry values for messages without explicit opcode
        for (const msg of spec.messages) {
            if (msg.opcode === undefined && registry[msg.name] !== undefined) {
                const regOpcode = registry[msg.name];
                if (usedOpcodes.has(regOpcode)) {
                    throw new Error(`Duplicate opcode from registry: ${regOpcode} for ${msg.name}`);
                }
                usedOpcodes.add(regOpcode);
                msg.opcode = regOpcode;
            }
        }

        // Phase 3: Auto-assign remaining messages (sorted by name for determinism)
        const unassigned = spec.messages
            .filter(m => m.opcode === undefined)
            .sort((a, b) => a.name.localeCompare(b.name));

        // Find max opcode to start auto-assign
        let nextOpcode = MIN_OPCODE;
        for (const oc of usedOpcodes) {
            if (oc >= nextOpcode) {
                nextOpcode = oc + 1;
            }
        }

        for (const msg of unassigned) {
            // Find next available opcode
            while (usedOpcodes.has(nextOpcode)) {
                nextOpcode++;
            }
            msg.opcode = nextOpcode;
            registry[msg.name] = nextOpcode;
            usedOpcodes.add(nextOpcode);
            nextOpcode++;
        }
    }

    assignTags(spec, registry) {
        const MIN_TAG = 1;
        const MAX_TAG = 536870911; // 2^29 - 1 (protobuf limit)
        const RESERVED_START = 19000;
        const RESERVED_END = 19999;

        for (const msg of spec.messages) {
            const usedTags = new Set();

            // Phase 1: Apply explicit tags from spec (highest priority)
            for (const field of msg.fields || []) {
                if (field.tag !== undefined) {
                    this.validateTag(field.tag, msg.name, field.name);
                    if (usedTags.has(field.tag)) {
                        throw new Error(`Duplicate tag in ${msg.name}: ${field.tag} for ${field.name}`);
                    }
                    usedTags.add(field.tag);
                    const key = `${msg.name}.${field.name}`;
                    registry[key] = field.tag;
                }
            }

            // Phase 2: Apply registry values for fields without explicit tag
            for (const field of msg.fields || []) {
                const key = `${msg.name}.${field.name}`;
                if (field.tag === undefined && registry[key] !== undefined) {
                    const regTag = registry[key];
                    this.validateTag(regTag, msg.name, field.name);
                    if (usedTags.has(regTag)) {
                        throw new Error(`Duplicate tag from registry in ${msg.name}: ${regTag} for ${field.name}`);
                    }
                    usedTags.add(regTag);
                    field.tag = regTag;
                }
            }

            // Phase 3: Auto-assign remaining fields (in order for determinism)
            let nextTag = MIN_TAG;
            for (const field of msg.fields || []) {
                if (field.tag === undefined) {
                    // Find next available tag, skipping reserved range
                    while (usedTags.has(nextTag) || 
                           (nextTag >= RESERVED_START && nextTag <= RESERVED_END)) {
                        nextTag++;
                        // Skip reserved range
                        if (nextTag >= RESERVED_START && nextTag <= RESERVED_END) {
                            nextTag = RESERVED_END + 1;
                        }
                    }
                    
                    if (nextTag > MAX_TAG) {
                        throw new Error(`Tag overflow in ${msg.name}.${field.name}`);
                    }

                    field.tag = nextTag;
                    const key = `${msg.name}.${field.name}`;
                    registry[key] = nextTag;
                    usedTags.add(nextTag);
                    nextTag++;
                }
            }
        }
    }

    validateTag(tag, msgName, fieldName) {
        const MIN_TAG = 1;
        const MAX_TAG = 536870911;
        const RESERVED_START = 19000;
        const RESERVED_END = 19999;

        if (tag < MIN_TAG || tag > MAX_TAG) {
            throw new Error(`Tag out of range in ${msgName}.${fieldName}: ${tag} (valid: ${MIN_TAG}-${MAX_TAG})`);
        }
        if (tag >= RESERVED_START && tag <= RESERVED_END) {
            throw new Error(`Tag in reserved range in ${msgName}.${fieldName}: ${tag} (reserved: ${RESERVED_START}-${RESERVED_END})`);
        }
    }

    // ========================================================================
    // Utilities
    // ========================================================================

    globFiles(dir, patterns) {
        if (!fs.existsSync(dir)) return [];

        const files = fs.readdirSync(dir);
        const result = [];

        for (const pattern of patterns) {
            const regex = new RegExp('^' + pattern.replace(/\*/g, '.*') + '$');
            for (const file of files) {
                if (regex.test(file)) {
                    result.push(path.join(dir, file));
                }
            }
        }

        return result;
    }

    // ========================================================================
    // Marker-based Index Management Utilities
    // ========================================================================

    /**
     * Read file content or return empty string if not exists
     */
    readTextOrEmpty(filePath) {
        if (fs.existsSync(filePath)) {
            return fs.readFileSync(filePath, 'utf-8');
        }
        return '';
    }

    /**
     * Write text to file with trailing newline
     */
    writeText(filePath, text) {
        const content = text.endsWith('\n') ? text : text + '\n';
        fs.writeFileSync(filePath, content);
    }

    /**
     * Ensure file exists, create with initial content if not
     */
    ensureFile(filePath, initialContent) {
        if (!fs.existsSync(filePath)) {
            fs.mkdirSync(path.dirname(filePath), { recursive: true });
            this.writeText(filePath, initialContent);
            return true; // created
        }
        return false; // already exists
    }

    /**
     * Update marker block in text content
     * Returns updated text or throws if markers not found
     */
    updateMarkerBlock(text, startMarker, endMarker, replacementLines) {
        const startIdx = text.indexOf(startMarker);
        const endIdx = text.indexOf(endMarker);

        if (startIdx === -1 || endIdx === -1) {
            throw new Error(`Marker not found: ${startMarker} or ${endMarker}`);
        }

        const before = text.substring(0, startIdx + startMarker.length);
        const after = text.substring(endIdx);

        const replacement = replacementLines.length > 0
            ? '\n' + replacementLines.join('\n') + '\n'
            : '\n';

        return before + replacement + after;
    }

    /**
     * Generate initial index.ts template with markers
     */
    generateDomainIndexTsTemplate(domainName) {
        return `// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System v10
// </auto-generated>

// <devian:domain-exports>
export * from './generated/${domainName}.g';
// </devian:domain-exports>

// <devian:feature-exports>
export * from './features';
// </devian:feature-exports>
`;
    }

    /**
     * Generate initial features/index.ts template with markers
     */
    generateFeaturesIndexTsTemplate() {
        return `// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System v10
// This file is auto-managed. Do not edit marker blocks.
// </auto-generated>

// <devian:feature-exports>
// </devian:feature-exports>
`;
    }

    /**
     * Scan features directory and return sorted export lines
     */
    scanFeaturesForExports(featuresDir) {
        if (!fs.existsSync(featuresDir)) {
            return [];
        }

        const entries = fs.readdirSync(featuresDir, { withFileTypes: true });
        const exports = [];

        for (const entry of entries) {
            const name = entry.name;

            // Skip exclusions
            if (name === 'index.ts') continue;
            if (name.startsWith('.')) continue;
            if (name === 'generated') continue;
            if (name.endsWith('.test.ts') || name.endsWith('.spec.ts')) continue;
            if (name.endsWith('.d.ts')) continue;

            if (entry.isDirectory()) {
                // Directory -> export * from './{dir}';
                exports.push({ name, line: `export * from './${name}';` });
            } else if (name.endsWith('.ts')) {
                // .ts file -> export * from './{basename}';
                const basename = name.slice(0, -3); // remove .ts
                exports.push({ name: basename, line: `export * from './${basename}';` });
            }
        }

        // Sort by name (localeCompare for deterministic order)
        exports.sort((a, b) => a.name.localeCompare(b.name));

        return exports.map(e => e.line);
    }

    /**
     * Update or create root index.ts with marker-based approach
     */
    updateDomainIndexTs(targetDir, domainName) {
        const indexPath = path.join(targetDir, 'index.ts');

        // Create template if not exists
        if (!fs.existsSync(indexPath)) {
            const template = this.generateDomainIndexTsTemplate(domainName);
            this.writeText(indexPath, template);
            console.log(`    [Create] ${indexPath}`);
            return;
        }

        // Update marker blocks
        let content = this.readTextOrEmpty(indexPath);

        // Update domain-exports block
        const domainExports = [`export * from './generated/${domainName}.g';`];
        try {
            content = this.updateMarkerBlock(
                content,
                '// <devian:domain-exports>',
                '// </devian:domain-exports>',
                domainExports
            );
        } catch (e) {
            // Marker not found - regenerate file
            console.log(`    [Warn] Marker not found in ${indexPath}, regenerating...`);
            const template = this.generateDomainIndexTsTemplate(domainName);
            this.writeText(indexPath, template);
            return;
        }

        // Update feature-exports block
        const featureExports = [`export * from './features';`];
        try {
            content = this.updateMarkerBlock(
                content,
                '// <devian:feature-exports>',
                '// </devian:feature-exports>',
                featureExports
            );
        } catch (e) {
            // Continue even if feature marker not found (legacy file)
            console.log(`    [Warn] Feature marker not found in ${indexPath}`);
        }

        this.writeText(indexPath, content);
        console.log(`    [Update] ${indexPath} (marker)`);
    }

    /**
     * Update or create features/index.ts with auto-scanned exports
     */
    updateFeaturesIndexTs(targetDir) {
        const featuresDir = path.join(targetDir, 'features');
        const featuresIndexPath = path.join(featuresDir, 'index.ts');

        // Ensure features directory exists
        if (!fs.existsSync(featuresDir)) {
            fs.mkdirSync(featuresDir, { recursive: true });
        }

        // Create template if not exists
        if (!fs.existsSync(featuresIndexPath)) {
            const template = this.generateFeaturesIndexTsTemplate();
            this.writeText(featuresIndexPath, template);
            console.log(`    [Create] ${featuresIndexPath}`);
        }

        // Scan features and update marker block
        const featureExports = this.scanFeaturesForExports(featuresDir);

        let content = this.readTextOrEmpty(featuresIndexPath);

        try {
            content = this.updateMarkerBlock(
                content,
                '// <devian:feature-exports>',
                '// </devian:feature-exports>',
                featureExports
            );
            this.writeText(featuresIndexPath, content);
            if (featureExports.length > 0) {
                console.log(`    [Update] ${featuresIndexPath} (${featureExports.length} exports)`);
            }
        } catch (e) {
            console.log(`    [Warn] Marker not found in ${featuresIndexPath}, regenerating...`);
            const template = this.generateFeaturesIndexTsTemplate();
            // Insert exports into template
            const updatedTemplate = this.updateMarkerBlock(
                template,
                '// <devian:feature-exports>',
                '// </devian:feature-exports>',
                featureExports
            );
            this.writeText(featuresIndexPath, updatedTemplate);
        }
    }

    cleanAndCopy(src, dest) {
        // Clean target
        if (fs.existsSync(dest)) {
            fs.rmSync(dest, { recursive: true });
        }
        fs.mkdirSync(dest, { recursive: true });

        // Copy files recursively
        if (!fs.existsSync(src)) return;

        this.copyDirRecursive(src, dest);
    }

    copyDirRecursive(src, dest) {
        const entries = fs.readdirSync(src, { withFileTypes: true });
        for (const entry of entries) {
            const srcPath = path.join(src, entry.name);
            const destPath = path.join(dest, entry.name);
            if (entry.isDirectory()) {
                fs.mkdirSync(destPath, { recursive: true });
                this.copyDirRecursive(srcPath, destPath);
            } else {
                fs.copyFileSync(srcPath, destPath);
            }
        }
    }

    ensureTsConfig(targetDir) {
        const tsconfigPath = path.join(targetDir, 'tsconfig.json');
        if (!fs.existsSync(tsconfigPath)) {
            const tsconfig = {
                extends: '../../tsconfig.json',
                compilerOptions: {
                    outDir: './dist'
                },
                include: ['./**/*.ts']
            };
            fs.writeFileSync(tsconfigPath, JSON.stringify(tsconfig, null, 2) + '\n');
        }
    }

    ensureCsProj(targetDir, moduleName) {
        const csprojPath = path.join(targetDir, `${moduleName}.csproj`);
        if (!fs.existsSync(csprojPath)) {
            fs.mkdirSync(targetDir, { recursive: true });
            const csproj = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>${moduleName}</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Devian.Core\\Devian.Core.csproj" />
  </ItemGroup>
</Project>
`;
            fs.writeFileSync(csprojPath, csproj);
        }
    }

    ensureModulePackageJson(targetDir, moduleName, domainName) {
        const packageJsonPath = path.join(targetDir, 'package.json');
        if (!fs.existsSync(packageJsonPath)) {
            const packageJson = {
                name: `@devian/module-${domainName.toLowerCase()}`,
                version: '10.0.0',
                main: 'index.ts',
                types: 'index.ts',
                dependencies: {
                    '@devian/core': '10.0.0'
                }
            };
            fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
        }
    }

    ensureProtocolPackageJson(targetDir, groupName, hasServerRuntime = false, hasClientRuntime = false) {
        const packageJsonPath = path.join(targetDir, 'package.json');
        
        // Build dependencies
        const dependencies = {
            '@devian/core': '10.0.0',
            '@devian/module-common': '10.0.0'
        };
        if (hasServerRuntime || hasClientRuntime) {
            dependencies['@devian/network'] = '10.0.0';
        }

        // Build exports
        const exports = {
            '.': './index.ts'
        };
        if (hasServerRuntime) {
            exports['./server-runtime'] = './generated/ServerRuntime.g.ts';
        }
        if (hasClientRuntime) {
            exports['./client-runtime'] = './generated/ClientRuntime.g.ts';
        }

        const packageJson = {
            name: `@devian/network-${groupName.toLowerCase()}`,
            version: '10.0.0',
            type: 'module',
            main: 'index.ts',
            types: 'index.ts',
            exports,
            dependencies
        };
        
        fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
    }

    // ========================================================================
    // UPM (Unity Package Manager) Support
    // ========================================================================

    generateDomainUpmScaffold(domainName, stagingCs) {
        const asmdefName = `Devian.Module.${domainName}`;
        const stagingUpm = path.join(this.tempDir, domainName, 'upm');
        const stagingRuntime = path.join(stagingUpm, 'Runtime');
        const stagingEditor = path.join(stagingUpm, 'Editor');

        fs.mkdirSync(stagingRuntime, { recursive: true });
        fs.mkdirSync(stagingEditor, { recursive: true });

        // package.json - SSOT: skills/devian/17-upm-package-metadata/SKILL.md
        const isCommon = domainName === 'Common';
        const dependencies = { 'com.devian.core': '0.1.0' };
        if (isCommon) {
            dependencies['com.unity.nuget.newtonsoft-json'] = '3.2.1';
        }

        const packageJsonObj = {
            name: `com.devian.module.${domainName.toLowerCase()}`,
            version: '0.1.0',
            displayName: `Devian Module ${domainName}`,
            description: isCommon
                ? 'Devian.Module.Common runtime for Unity (source) - Common features'
                : `Devian.Module.${domainName} runtime for Unity (source)`,
            unity: '2021.3',
            author: { name: 'Kim, Hyong Joon' },
            dependencies
        };
        fs.writeFileSync(path.join(stagingUpm, 'package.json'), JSON.stringify(packageJsonObj, null, 2));

        // Runtime.asmdef - SSOT: skills/devian/19-unity-module-common-upm/SKILL.md
        const asmdefReferences = isCommon
            ? ['Devian.Core', 'Newtonsoft.Json']
            : ['Devian.Core'];
        
        const runtimeAsmdef = {
            name: asmdefName,
            rootNamespace: asmdefName,
            references: asmdefReferences,
            includePlatforms: [],
            excludePlatforms: [],
            allowUnsafeCode: false,
            overrideReferences: false,
            precompiledReferences: [],
            autoReferenced: true,
            defineConstraints: [],
            versionDefines: [],
            noEngineReferences: false
        };
        fs.writeFileSync(path.join(stagingRuntime, `${asmdefName}.asmdef`), JSON.stringify(runtimeAsmdef, null, 2));

        // Editor.asmdef
        const editorAsmdef = {
            name: `${asmdefName}.Editor`,
            rootNamespace: `${asmdefName}.Editor`,
            references: [asmdefName],
            includePlatforms: ['Editor'],
            excludePlatforms: [],
            allowUnsafeCode: false,
            overrideReferences: false,
            precompiledReferences: [],
            autoReferenced: true,
            defineConstraints: [],
            versionDefines: [],
            noEngineReferences: false
        };
        fs.writeFileSync(path.join(stagingEditor, `${asmdefName}.Editor.asmdef`), JSON.stringify(editorAsmdef, null, 2));

        // Copy C# generated files to Runtime
        if (fs.existsSync(stagingCs)) {
            for (const file of fs.readdirSync(stagingCs)) {
                if (file.endsWith('.cs')) {
                    fs.copyFileSync(
                        path.join(stagingCs, file),
                        path.join(stagingRuntime, file)
                    );
                }
            }
        }

        // Common 모듈일 때 Features 폴더 복사 (Logger/Variant/Complex)
        // SSOT: skills/devian/19-unity-module-common-upm/SKILL.md
        if (isCommon) {
            const featuresSource = path.join(this.rootDir, 'framework-cs/modules/Devian.Module.Common/features');
            const featuresTarget = path.join(stagingRuntime, 'Features');
            
            if (fs.existsSync(featuresSource)) {
                this.copyDirRecursive(featuresSource, featuresTarget, '.cs');
                console.log(`    [UPM] Copied Features to staging: ${featuresTarget}`);
            }
        }
    }

    /**
     * Recursively copy directory with optional file extension filter.
     * @param {string} src Source directory
     * @param {string} dest Destination directory
     * @param {string} [extFilter] Optional file extension filter (e.g., '.cs')
     */
    copyDirRecursive(src, dest, extFilter = null) {
        fs.mkdirSync(dest, { recursive: true });
        
        for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
            const srcPath = path.join(src, entry.name);
            const destPath = path.join(dest, entry.name);
            
            if (entry.isDirectory()) {
                this.copyDirRecursive(srcPath, destPath, extFilter);
            } else if (entry.isFile()) {
                if (!extFilter || entry.name.endsWith(extFilter)) {
                    fs.copyFileSync(srcPath, destPath);
                }
            }
        }
    }

    // ========================================================================
    // Static UPM Package Processing (e.g., com.devian.unity.common)
    // SSOT: skills/devian/21-unity-common-upm/SKILL.md
    // ========================================================================

    /**
     * Process static UPM package: copy source to staging.
     * @param {Object} pkgConfig - { name, sourceDir, upmTargetDir }
     */
    async processStaticUpmPackage(pkgConfig) {
        const { name, sourceDir } = pkgConfig;
        console.log(`  [StaticUPM] ${name}`);

        const sourcePath = this.resolvePath(sourceDir);
        const stagingUpm = path.join(this.tempDir, `static-${name}`);

        if (!fs.existsSync(sourcePath)) {
            console.log(`    [SKIP] Source not found: ${sourcePath}`);
            return;
        }

        // Copy entire source to staging
        this.copyDirRecursive(sourcePath, stagingUpm);
        console.log(`    [OK] Staged to ${stagingUpm}`);
    }

    /**
     * Copy static UPM package from staging to target (clean+copy).
     * @param {Object} pkgConfig - { name, sourceDir, upmTargetDir }
     */
    async copyStaticUpmPackageToTarget(pkgConfig) {
        const { name, upmTargetDir } = pkgConfig;
        
        const stagingUpm = path.join(this.tempDir, `static-${name}`);
        const targetPath = path.join(this.resolvePath(upmTargetDir), name);

        if (!fs.existsSync(stagingUpm)) {
            console.log(`  [SKIP] ${name}: staging not found`);
            return;
        }

        // Clean target
        if (fs.existsSync(targetPath)) {
            fs.rmSync(targetPath, { recursive: true });
        }

        // Copy staging to target
        this.copyDirRecursive(stagingUpm, targetPath);
        console.log(`  [UPM] ${name} → ${targetPath}`);
    }

    generateProtocolUpmScaffold(groupName, stagingCs) {
        const csProjectName = `Devian.Network.${groupName}`;
        const stagingUpm = path.join(this.tempDir, `${csProjectName}-upm`);
        const stagingRuntime = path.join(stagingUpm, 'Runtime');
        const stagingEditor = path.join(stagingUpm, 'Editor');

        fs.mkdirSync(stagingRuntime, { recursive: true });
        fs.mkdirSync(stagingEditor, { recursive: true });

        // package.json
        const packageJson = JSON.stringify({
            name: `com.devian.protocol.${groupName.toLowerCase()}`,
            version: '1.0.0',
            displayName: `Devian Protocol ${groupName}`,
            description: 'Generated by Devian Build System',
            unity: '2021.3'
        }, null, 2);
        fs.writeFileSync(path.join(stagingUpm, 'package.json'), packageJson);

        // Runtime.asmdef
        const runtimeAsmdef = JSON.stringify({
            name: csProjectName,
            references: ['Devian.Core', 'Devian.Network', 'Devian.Module.Common'],
            includePlatforms: [],
            excludePlatforms: []
        }, null, 2);
        fs.writeFileSync(path.join(stagingRuntime, `${csProjectName}.asmdef`), runtimeAsmdef);

        // Editor.asmdef
        const editorAsmdef = JSON.stringify({
            name: `${csProjectName}.Editor`,
            references: [csProjectName],
            includePlatforms: ['Editor'],
            excludePlatforms: []
        }, null, 2);
        fs.writeFileSync(path.join(stagingEditor, `${csProjectName}.Editor.asmdef`), editorAsmdef);

        // Copy C# generated files to Runtime
        if (fs.existsSync(stagingCs)) {
            for (const file of fs.readdirSync(stagingCs)) {
                if (file.endsWith('.cs')) {
                    fs.copyFileSync(
                        path.join(stagingCs, file),
                        path.join(stagingRuntime, file)
                    );
                }
            }
        }
    }

    copyUpmToTarget(stagingUpm, targetDir) {
        if (!fs.existsSync(stagingUpm)) return;

        fs.mkdirSync(targetDir, { recursive: true });

        // Scaffold files (don't overwrite if exist)
        const packageJsonSrc = path.join(stagingUpm, 'package.json');
        const packageJsonDest = path.join(targetDir, 'package.json');
        if (fs.existsSync(packageJsonSrc) && !fs.existsSync(packageJsonDest)) {
            fs.copyFileSync(packageJsonSrc, packageJsonDest);
        }

        // Sync samples metadata if Samples~ folder exists
        this.syncSamplesMetadata(targetDir);

        // Editor folder (don't overwrite if exist)
        const stagingEditor = path.join(stagingUpm, 'Editor');
        const targetEditor = path.join(targetDir, 'Editor');
        if (fs.existsSync(stagingEditor)) {
            fs.mkdirSync(targetEditor, { recursive: true });
            for (const file of fs.readdirSync(stagingEditor)) {
                const dest = path.join(targetEditor, file);
                if (!fs.existsSync(dest)) {
                    fs.copyFileSync(path.join(stagingEditor, file), dest);
                }
            }
        }

        // Runtime folder (clean & copy)
        const stagingRuntime = path.join(stagingUpm, 'Runtime');
        const targetRuntime = path.join(targetDir, 'Runtime');
        this.cleanAndCopy(stagingRuntime, targetRuntime);
    }

    /**
     * Sync samples metadata in package.json based on Samples~ folder contents.
     * If Samples~ folder exists with subfolders, automatically adds/updates samples field.
     * @param {string} packageDir - UPM package directory
     */
    syncSamplesMetadata(packageDir) {
        const packageJsonPath = path.join(packageDir, 'package.json');
        const samplesDir = path.join(packageDir, 'Samples~');

        // Skip if no package.json
        if (!fs.existsSync(packageJsonPath)) return;

        // Check if Samples~ folder exists
        if (!fs.existsSync(samplesDir)) return;

        // Get sample folders
        const sampleFolders = fs.readdirSync(samplesDir, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory())
            .map(dirent => dirent.name);

        // Skip if no sample folders
        if (sampleFolders.length === 0) return;

        // Read existing package.json
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

        // Build samples array from folder structure
        const samples = sampleFolders.map(folderName => {
            const samplePath = `Samples~/${folderName}`;
            
            // Check for existing sample entry to preserve displayName/description
            const existingSample = (packageJson.samples || [])
                .find(s => s.path === samplePath);

            if (existingSample) {
                return existingSample;
            }

            // Generate default metadata for new samples
            return {
                displayName: this.folderNameToDisplayName(folderName),
                description: `Sample: ${folderName}`,
                path: samplePath
            };
        });

        // Update samples field
        packageJson.samples = samples;

        // Write back with 2-space indent
        fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
        console.log(`      [UPM] Synced ${samples.length} sample(s) in ${path.basename(packageDir)}/package.json`);
    }

    /**
     * Convert folder name to display name (e.g., "BasicWsClient" -> "Basic Ws Client")
     * @param {string} folderName - Folder name
     * @returns {string} - Human-readable display name
     */
    folderNameToDisplayName(folderName) {
        // Insert space before uppercase letters and trim
        return folderName
            .replace(/([A-Z])/g, ' $1')
            .replace(/^[\s]/, '')
            .trim();
    }

    /**
     * Convert asmdef reference name to UPM package name.
     * @param {string} asmdefRef - Assembly reference name (e.g., "Devian.Core", "Devian.Module.Common")
     * @returns {string|null} - UPM package name or null if not mappable
     */
    asmdefRefToUpmPackage(asmdefRef) {
        const mapping = {
            'Devian.Core': 'com.devian.core',
            'Devian.Network': 'com.devian.network',
            'Devian.Protobuf': 'com.devian.protobuf',
        };

        // Direct mapping
        if (mapping[asmdefRef]) {
            return mapping[asmdefRef];
        }

        // Pattern: Devian.Module.{Domain} -> com.devian.module.{domain}
        const moduleMatch = asmdefRef.match(/^Devian\.Module\.(\w+)$/);
        if (moduleMatch) {
            return `com.devian.module.${moduleMatch[1].toLowerCase()}`;
        }

        // Skip self-references or unknown packages
        return null;
    }

    /**
     * Scan Runtime/Generated.* folders for asmdef files and extract their references.
     * Updates package.json dependencies based on asmdef references.
     * @param {string} packageDir - UPM package directory
     */
    syncGeneratedDependencies(packageDir) {
        const packageJsonPath = path.join(packageDir, 'package.json');
        const runtimeDir = path.join(packageDir, 'Runtime');

        // Skip if no package.json or Runtime folder
        if (!fs.existsSync(packageJsonPath)) return;
        if (!fs.existsSync(runtimeDir)) return;

        // Find Generated.* folders
        const generatedFolders = fs.readdirSync(runtimeDir, { withFileTypes: true })
            .filter(dirent => dirent.isDirectory() && dirent.name.startsWith('Generated.'))
            .map(dirent => path.join(runtimeDir, dirent.name));

        if (generatedFolders.length === 0) return;

        // Collect all asmdef references
        const allRefs = new Set();

        for (const folder of generatedFolders) {
            // Find all .asmdef files recursively
            const findAsmdefFiles = (dir) => {
                const files = [];
                const entries = fs.readdirSync(dir, { withFileTypes: true });
                for (const entry of entries) {
                    const fullPath = path.join(dir, entry.name);
                    if (entry.isDirectory()) {
                        files.push(...findAsmdefFiles(fullPath));
                    } else if (entry.name.endsWith('.asmdef')) {
                        files.push(fullPath);
                    }
                }
                return files;
            };

            const asmdefFiles = findAsmdefFiles(folder);
            
            for (const asmdefPath of asmdefFiles) {
                try {
                    const asmdef = JSON.parse(fs.readFileSync(asmdefPath, 'utf-8'));
                    if (asmdef.references && Array.isArray(asmdef.references)) {
                        for (const ref of asmdef.references) {
                            allRefs.add(ref);
                        }
                    }
                } catch (e) {
                    console.warn(`      [WARN] Failed to parse ${asmdefPath}: ${e.message}`);
                }
            }
        }

        if (allRefs.size === 0) return;

        // Read existing package.json
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));
        const existingDeps = packageJson.dependencies || {};

        // Default versions for packages (can be improved by scanning actual packages)
        const defaultVersions = {
            'com.devian.core': '0.1.0',
            'com.devian.network': '0.1.0',
            'com.devian.protobuf': '0.1.0',
            'com.devian.module.common': '0.1.0',
            'com.devian.unity.common': '0.1.0',
        };

        // Convert refs to UPM packages and add to dependencies
        let addedCount = 0;
        for (const ref of allRefs) {
            const upmPackage = this.asmdefRefToUpmPackage(ref);
            if (upmPackage && !existingDeps[upmPackage]) {
                const version = defaultVersions[upmPackage] || '1.0.0';
                existingDeps[upmPackage] = version;
                addedCount++;
            }
        }

        if (addedCount > 0) {
            packageJson.dependencies = existingDeps;
            fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
            console.log(`      [UPM] Added ${addedCount} generated dependencies in ${path.basename(packageDir)}/package.json`);
        }
    }

    /**
     * Sync samples metadata for all UPM packages in configured upmTargetDirs.
     * Scans for packages with Samples~ folders and updates their package.json.
     */
    async syncAllUpmSamples() {
        // Collect all unique upmTargetDirs from config
        const upmTargetDirs = new Set();

        if (this.config.domains) {
            for (const domainConfig of Object.values(this.config.domains)) {
                if (domainConfig.upmTargetDir) {
                    upmTargetDirs.add(this.resolvePath(domainConfig.upmTargetDir));
                }
            }
        }

        if (this.config.protocols && Array.isArray(this.config.protocols)) {
            for (const protocolConfig of this.config.protocols) {
                if (protocolConfig.upmTargetDir) {
                    upmTargetDirs.add(this.resolvePath(protocolConfig.upmTargetDir));
                }
            }
        }

        if (upmTargetDirs.size === 0) {
            console.log('  No UPM target directories configured, skipping samples sync.');
            return;
        }

        // Scan each upmTargetDir for UPM packages with Samples~ folders
        for (const packagesDir of upmTargetDirs) {
            if (!fs.existsSync(packagesDir)) continue;

            console.log(`  [Scan] ${packagesDir}`);

            // List subdirectories (each should be a UPM package)
            const entries = fs.readdirSync(packagesDir, { withFileTypes: true });
            for (const entry of entries) {
                if (!entry.isDirectory()) continue;

                const packageDir = path.join(packagesDir, entry.name);
                const packageJsonPath = path.join(packageDir, 'package.json');
                const samplesDir = path.join(packageDir, 'Samples~');

                // Skip if not a UPM package (no package.json)
                if (!fs.existsSync(packageJsonPath)) continue;

                // Skip if no Samples~ folder
                if (!fs.existsSync(samplesDir)) continue;

                // Sync samples metadata
                this.syncSamplesMetadata(packageDir);

                // Sync generated dependencies from Runtime/Generated.* asmdef files
                this.syncGeneratedDependencies(packageDir);
            }
        }
    }

    // ========================================================================
    // Forbidden Namespace Guard (재발 방지)
    // SSOT: skills/devian-common/01-module-policy/SKILL.md
    // ========================================================================

    checkForbiddenNamespaces() {
        const forbiddenPattern = 'Devian.Module.Common.Features';
        const targetDirs = [
            path.join(this.rootDir, 'framework-cs/modules/Devian.Module.Common'),
            path.join(this.rootDir, 'framework-cs/apps/UnityExample/Packages/com.devian.module.common'),
            path.join(this.rootDir, 'framework-cs/apps/UnityExample/Packages/com.devian.unity.common'),
        ];

        const violations = [];

        for (const dir of targetDirs) {
            if (!fs.existsSync(dir)) continue;
            const found = this.scanForForbiddenNamespace(dir, forbiddenPattern);
            violations.push(...found);
        }

        if (violations.length > 0) {
            console.error('\n[FAIL] Forbidden namespace detected!');
            console.error(`Pattern: ${forbiddenPattern}`);
            console.error('Violations:');
            for (const v of violations) {
                console.error(`  - ${v.file}:${v.line}: ${v.content.trim()}`);
            }
            throw new Error(
                `Forbidden namespace detected: ${forbiddenPattern} (Common must use Devian.Module.Common only).`
            );
        }

        console.log('  [OK] No forbidden namespaces found.');
    }

    scanForForbiddenNamespace(dir, pattern) {
        const results = [];
        const entries = fs.readdirSync(dir, { withFileTypes: true });

        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);

            if (entry.isDirectory()) {
                results.push(...this.scanForForbiddenNamespace(fullPath, pattern));
            } else if (entry.isFile() && entry.name.endsWith('.cs')) {
                const content = fs.readFileSync(fullPath, 'utf-8');
                const lines = content.split('\n');

                for (let i = 0; i < lines.length; i++) {
                    if (lines[i].includes(pattern)) {
                        results.push({
                            file: fullPath,
                            line: i + 1,
                            content: lines[i],
                        });
                    }
                }
            }
        }

        return results;
    }
}

// ============================================================================
// Main Entry Point
// ============================================================================

async function main() {
    const args = process.argv.slice(2);

    if (args.length < 1) {
        console.log('Usage: node build.js <build.json>');
        console.log('Example: node build.js ../../../input/build.json');
        process.exit(1);
    }

    const buildJsonPath = args[0];

    try {
        const runner = new DevianToolBuilder(buildJsonPath);
        await runner.run();
    } catch (error) {
        console.error('Build failed:', error.message);
        console.error(error.stack);
        process.exit(1);
    }
}

main();
