// <auto-generated>
// Unity Singleton - ResSingleton<T>
// SSOT: skills/devian-unity/30-unity-components/01-singleton/SKILL.md
// </auto-generated>

using System;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// Resources-based singleton - loads prefab from Resources folder.
    /// Only this type allows Resources.Load usage.
    /// Instance requires prior Load(resourcePath) call.
    /// </summary>
    /// <typeparam name="T">Concrete singleton type</typeparam>
    public abstract class ResSingleton<T> : MonoBehaviour where T : ResSingleton<T>
    {
        private static T _instance;
        private static readonly object _lock = new object();
        
        /// <summary>
        /// Returns true if an instance exists.
        /// </summary>
        public static bool HasInstance => _instance != null;
        
        /// <summary>
        /// Gets the singleton instance.
        /// Throws InvalidOperationException if Load() was not called first.
        /// </summary>
        public static T Instance
        {
            get
            {
                if (_instance == null)
                {
                    throw new InvalidOperationException(
                        $"[{typeof(T).Name}] Instance not found. " +
                        "Call Load(resourcePath) first to create the singleton.");
                }
                return _instance;
            }
        }
        
        /// <summary>
        /// Loads and instantiates the singleton from Resources.
        /// Main thread only. If already loaded, returns existing instance.
        /// </summary>
        /// <param name="resourcePath">Path within Resources folder (without extension)</param>
        /// <returns>The singleton instance</returns>
        public static T Load(string resourcePath)
        {
            // Main thread check
            UnityMainThread.EnsureOrThrow($"{typeof(T).Name}.Load");
            
            if (string.IsNullOrEmpty(resourcePath))
                throw new ArgumentException("resourcePath cannot be null or empty", nameof(resourcePath));
            
            lock (_lock)
            {
                // Already loaded - return existing
                if (_instance != null)
                    return _instance;
                
                // Load prefab
                var prefab = Resources.Load<GameObject>(resourcePath);
                if (prefab == null)
                {
                    throw new InvalidOperationException(
                        $"[{typeof(T).Name}] Failed to load prefab at 'Resources/{resourcePath}'. " +
                        "Ensure the prefab exists in a Resources folder.");
                }
                
                // Instantiate
                var go = Instantiate(prefab);
                go.name = $"[{typeof(T).Name}]";
                
                // Get component
                var component = go.GetComponent<T>();
                if (component == null)
                {
                    UnityEngine.Object.Destroy(go);
                    throw new InvalidOperationException(
                        $"[{typeof(T).Name}] Prefab at 'Resources/{resourcePath}' " +
                        $"does not have component {typeof(T).Name}.");
                }
                
                _instance = component;
                DontDestroyOnLoad(go);
                
                return _instance;
            }
        }
        
        /// <summary>
        /// Called by Unity. Handles duplicate detection.
        /// </summary>
        protected virtual void Awake()
        {
            lock (_lock)
            {
                if (_instance != null && _instance != this)
                {
                    Debug.LogWarning($"[{typeof(T).Name}] Duplicate instance detected. Destroying this.");
                    UnityEngine.Object.Destroy(gameObject);
                    return;
                }
                
                _instance = (T)this;
                DontDestroyOnLoad(gameObject);
            }
        }
        
        /// <summary>
        /// Called by Unity. Clears instance reference if this is the registered instance.
        /// </summary>
        protected virtual void OnDestroy()
        {
            lock (_lock)
            {
                if (_instance == this)
                {
                    _instance = null;
                }
            }
        }
    }
}
