// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using System;
using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{
    /// <summary>
    /// C# 테이블 Row 클래스 생성기.
    /// 
    /// 생성 규칙:
    /// - partial class로 생성 (manual 코드와 분리)
    /// - IProtoEntity&lt;TProto&gt; 구현
    /// - _LoadProto/_SaveProto/_LoadJson/_SaveJson 메소드 생성
    /// - protobuf JSON은 JsonFormatter/JsonParser 사용
    /// </summary>
    public static class CSharpTableGenerator
    {
        /// <summary>
        /// Row 클래스 생성 (IProtoEntity 구현 포함)
        /// </summary>
        public static string Generate(TableSpec spec, string ns)
        {
            var sb = new StringBuilder();
            var protoTypeName = spec.RowTypeName;

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Devian.Core;");
            sb.AppendLine("using Devian.Protobuf;");
            sb.AppendLine("using Google.Protobuf;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // Row class (partial, IProtoEntity<TProto> 구현)
            sb.AppendLine($"    public sealed partial class {spec.RowTypeName} : IProtoEntity<Proto.{protoTypeName}>");
            sb.AppendLine("    {");

            // Properties
            foreach (var col in spec.Columns)
            {
                try
                {
                    var csType = TypeMapper.ToCSharpType(col.Type);
                    var propName = toPascalCase(col.Name);

                    if (!string.IsNullOrEmpty(col.Comment))
                    {
                        sb.AppendLine($"        /// <summary>{col.Comment}</summary>");
                    }
                    sb.AppendLine($"        public {csType} {propName} {{ get; set; }}");
                    sb.AppendLine();
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException(
                        $"[table='{spec.TableName}', column='{col.Name}', type='{col.Type}'] Type conversion failed: {ex.Message}", ex);
                }
            }

            // IEntity.GetKey() implementation
            var pkField = spec.Columns[spec.PrimaryKeyColumnIndex];
            var pkPropName = toPascalCase(pkField.Name);
            sb.AppendLine($"        /// <summary>Primary key 반환</summary>");
            sb.AppendLine($"        public object GetKey() => {pkPropName};");
            sb.AppendLine();

            // === IProtoEntity 구현 ===
            sb.AppendLine("        #region IProtoEntity Implementation");
            sb.AppendLine();

            // _LoadProto
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Protobuf 메시지에서 엔티티 필드 로드.");
            sb.AppendLine("        /// 의미 변환(암호화 복호화 등)의 중심.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public void _LoadProto(Proto.{protoTypeName} msg)");
            sb.AppendLine("        {");
            foreach (var col in spec.Columns)
            {
                var propName = toPascalCase(col.Name);
                var protoField = toPascalCase(col.Name);
                
                if (col.IsArray)
                {
                    sb.AppendLine($"            {propName} = new List<{TypeMapper.ToCSharpType(TypeMapper.StripArray(col.Type))}>(msg.{protoField});");
                }
                else
                {
                    sb.AppendLine($"            {propName} = msg.{protoField};");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // _SaveProto
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 엔티티 필드를 Protobuf 메시지로 저장.");
            sb.AppendLine("        /// 의미 변환(암호화 등)의 중심.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        public Proto.{protoTypeName} _SaveProto()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var msg = new Proto.{protoTypeName}();");
            foreach (var col in spec.Columns)
            {
                var propName = toPascalCase(col.Name);
                var protoField = toPascalCase(col.Name);
                
                if (col.IsArray)
                {
                    sb.AppendLine($"            if ({propName} != null) msg.{protoField}.AddRange({propName});");
                }
                else
                {
                    sb.AppendLine($"            msg.{protoField} = {propName};");
                }
            }
            sb.AppendLine("            return msg;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // _LoadJson
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Protobuf JSON 문자열에서 엔티티 로드.");
            sb.AppendLine("        /// JsonParser로 TProto 생성 후 _LoadProto 호출.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public void _LoadJson(string json)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var parser = new JsonParser(JsonParser.Settings.Default);");
            sb.AppendLine($"            var msg = parser.Parse<Proto.{protoTypeName}>(json);");
            sb.AppendLine("            _LoadProto(msg);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // _SaveJson
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// 엔티티를 Protobuf JSON 문자열로 저장.");
            sb.AppendLine("        /// _SaveProto 호출 후 JsonFormatter로 변환.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public string _SaveJson()");
            sb.AppendLine("        {");
            sb.AppendLine("            var msg = _SaveProto();");
            sb.AppendLine($"            var formatter = new JsonFormatter(JsonFormatter.Settings.Default);");
            sb.AppendLine("            return formatter.Format(msg);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        #endregion");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Table 클래스 생성 (Dictionary 기반)
        /// 
        /// 생성 규칙:
        /// - ITableContainer 구현
        /// - LoadFromJson/SaveToJson: NDJSON (1 row = 1 line)
        /// - LoadFromBase64/SaveToBase64: Bootstrap._Encode/_Decode 호출
        /// - Clear(): 캐시 정리
        /// 
        /// TODO: 현재 구현은 protobuf JsonParser/JsonFormatter 기반(레거시).
        ///       28 정본 파이프라인(Descriptor-driven IMessage build + 매핑 규칙)으로 마이그레이션 필요.
        /// </summary>
        public static string GenerateTable(TableSpec spec, string ns)
        {
            var sb = new StringBuilder();
            var pkType = TypeMapper.ToCSharpType(spec.PrimaryKeyTypeKey);
            var protoTypeName = spec.RowTypeName;

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using Devian.Core;");
            sb.AppendLine("using Google.Protobuf;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // Table class implementing ITableContainer
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {spec.TableName} 테이블 컨테이너.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public sealed class TB_{spec.TableName} : ITableContainer");
            sb.AppendLine("    {");
            
            // Fields
            sb.AppendLine($"        private readonly Dictionary<{pkType}, {spec.RowTypeName}> _map = new();");
            sb.AppendLine($"        private readonly List<{spec.RowTypeName}> _rows = new();");
            sb.AppendLine();
            
            // Properties
            sb.AppendLine($"        public IReadOnlyList<{spec.RowTypeName}> Rows => _rows;");
            sb.AppendLine("        public int Count => _rows.Count;");
            sb.AppendLine();
            
            // Get/TryGet
            var pkPropName = toPascalCase(spec.PrimaryKeyFieldName);
            sb.AppendLine($"        public {spec.RowTypeName}? Get({pkType} key) => _map.TryGetValue(key, out var row) ? row : null;");
            sb.AppendLine($"        public bool TryGet({pkType} key, out {spec.RowTypeName}? row) => _map.TryGetValue(key, out row);");
            sb.AppendLine($"        public {spec.RowTypeName} this[{pkType} key] => _map[key];");
            sb.AppendLine($"        public bool ContainsKey({pkType} key) => _map.ContainsKey(key);");
            sb.AppendLine();
            
            // Clear (ITableContainer)
            sb.AppendLine("        /// <inheritdoc/>");
            sb.AppendLine("        public void Clear()");
            sb.AppendLine("        {");
            sb.AppendLine("            _map.Clear();");
            sb.AppendLine("            _rows.Clear();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // LoadFromJson (ITableContainer)
            sb.AppendLine("        /// <inheritdoc/>");
            sb.AppendLine("        public void LoadFromJson(string json, LoadMode mode = LoadMode.Merge)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (mode == LoadMode.Replace) Clear();");
            sb.AppendLine();
            sb.AppendLine("            var parser = new JsonParser(JsonParser.Settings.Default);");
            sb.AppendLine("            var lines = json.Split('\\n', StringSplitOptions.RemoveEmptyEntries);");
            sb.AppendLine("            foreach (var line in lines)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (string.IsNullOrWhiteSpace(line)) continue;");
            sb.AppendLine();
            sb.AppendLine($"                var msg = parser.Parse<Proto.{protoTypeName}>(line);");
            sb.AppendLine($"                var row = new {spec.RowTypeName}();");
            sb.AppendLine("                row._LoadProto(msg);");
            sb.AppendLine();
            sb.AppendLine($"                var key = row.{pkPropName};");
            sb.AppendLine("                if (_map.ContainsKey(key))");
            sb.AppendLine("                {");
            sb.AppendLine("                    var idx = _rows.FindIndex(r => r.GetKey()!.Equals(key));");
            sb.AppendLine("                    if (idx >= 0) _rows[idx] = row;");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    _rows.Add(row);");
            sb.AppendLine("                }");
            sb.AppendLine("                _map[key] = row;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // SaveToJson (ITableContainer)
            sb.AppendLine("        /// <inheritdoc/>");
            sb.AppendLine("        public string SaveToJson()");
            sb.AppendLine("        {");
            sb.AppendLine("            var sb = new StringBuilder();");
            sb.AppendLine("            var formatter = new JsonFormatter(JsonFormatter.Settings.Default);");
            sb.AppendLine();
            sb.AppendLine("            foreach (var row in _rows)");
            sb.AppendLine("            {");
            sb.AppendLine("                var proto = row._SaveProto();");
            sb.AppendLine("                sb.AppendLine(formatter.Format(proto));");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            return sb.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // LoadFromBase64 (ITableContainer)
            sb.AppendLine("        /// <inheritdoc/>");
            sb.AppendLine("        public void LoadFromBase64(string base64, LoadMode mode = LoadMode.Merge)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (mode == LoadMode.Replace) Clear();");
            sb.AppendLine();
            sb.AppendLine("            var bytes = Convert.FromBase64String(base64);");
            sb.AppendLine($"            var rows = Bootstrap._Decode_{spec.TableName}(bytes);");
            sb.AppendLine("            foreach (var row in rows)");
            sb.AppendLine("            {");
            sb.AppendLine($"                var key = row.{pkPropName};");
            sb.AppendLine("                if (_map.ContainsKey(key))");
            sb.AppendLine("                {");
            sb.AppendLine("                    var idx = _rows.FindIndex(r => r.GetKey()!.Equals(key));");
            sb.AppendLine("                    if (idx >= 0) _rows[idx] = row;");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    _rows.Add(row);");
            sb.AppendLine("                }");
            sb.AppendLine("                _map[key] = row;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            
            // SaveToBase64 (ITableContainer)
            sb.AppendLine("        /// <inheritdoc/>");
            sb.AppendLine("        public string SaveToBase64()");
            sb.AppendLine("        {");
            sb.AppendLine($"            var bytes = Bootstrap._Encode_{spec.TableName}(_rows);");
            sb.AppendLine("            return Convert.ToBase64String(bytes);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string toPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return char.ToUpper(input[0]) + (input.Length > 1 ? input[1..] : "");
        }
    }
}
