// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using System.Text;
using System.Text.Json;

namespace Devian.Tools.Generators
{

    /// <summary>
    /// C# Contract (enum/class) 생성기
    /// contracts.json → C# enum/class
    /// </summary>
    public static class CSharpContractGenerator
    {
        /// <summary>
        /// Contract JSON → C# 코드 생성
        /// </summary>
        public static string Generate(JsonDocument doc, string ns)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            var root = doc.RootElement;

            // enums
            if (root.TryGetProperty("enums", out var enums))
            {
                foreach (var enumDef in enums.EnumerateArray())
                {
                    generateEnum(sb, enumDef);
                    sb.AppendLine();
                }
            }

            // classes
            if (root.TryGetProperty("classes", out var classes))
            {
                foreach (var classDef in classes.EnumerateArray())
                {
                    generateClass(sb, classDef);
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");

            return sb.ToString().TrimEnd();
        }

        private static void generateEnum(StringBuilder sb, JsonElement enumDef)
        {
            var name = enumDef.GetProperty("name").GetString();
            var values = enumDef.GetProperty("values");

            sb.AppendLine($"    public enum {name}");
            sb.AppendLine("    {");

            foreach (var val in values.EnumerateArray())
            {
                var valName = val.GetProperty("name").GetString();
                var valValue = val.GetProperty("value").GetInt32();
                sb.AppendLine($"        {valName} = {valValue},");
            }

            sb.AppendLine("    }");
        }

        private static void generateClass(StringBuilder sb, JsonElement classDef)
        {
            var name = classDef.GetProperty("name").GetString();
            var fields = classDef.GetProperty("fields");

            sb.AppendLine($"    public class {name}");
            sb.AppendLine("    {");

            foreach (var field in fields.EnumerateArray())
            {
                var fieldName = field.GetProperty("name").GetString();
                var fieldType = field.GetProperty("type").GetString();
                var csType = TypeMapper.ToCSharpType(fieldType!);
                sb.AppendLine($"        public {csType} {fieldName} {{ get; set; }}");
            }

            sb.AppendLine("    }");
        }
    }
}
