// <auto-generated>
// Devian Build System - C# Contract Generator
// </auto-generated>

using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{
    /// <summary>
    /// Contract Spec → C# 코드 생성 (64-contractgen-implementation)
    /// </summary>
    public static class CSharpContractGenerator
    {
        public static string Generate(ContractSpec spec, string domain)
        {
            var sb = new StringBuilder();
            var ns = $"Devian.{domain}";

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // Enums
            if (spec.Enums != null)
            {
                foreach (var e in spec.Enums)
                {
                    GenerateEnum(sb, e);
                    sb.AppendLine();
                }
            }

            // Classes
            if (spec.Classes != null)
            {
                foreach (var c in spec.Classes)
                {
                    GenerateClass(sb, c);
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            return sb.ToString().TrimEnd();
        }

        private static void GenerateEnum(StringBuilder sb, EnumSpec e)
        {
            if (!string.IsNullOrEmpty(e.Doc))
            {
                sb.AppendLine($"    /// <summary>{e.Doc}</summary>");
            }
            sb.AppendLine($"    public enum {e.Name}");
            sb.AppendLine("    {");

            for (int i = 0; i < e.Values.Count; i++)
            {
                var v = e.Values[i];
                var comma = i < e.Values.Count - 1 ? "," : "";
                sb.AppendLine($"        {v.Name} = {v.Value}{comma}");
            }

            sb.AppendLine("    }");
        }

        private static void GenerateClass(StringBuilder sb, ClassSpec c)
        {
            if (!string.IsNullOrEmpty(c.Doc))
            {
                sb.AppendLine($"    /// <summary>{c.Doc}</summary>");
            }
            sb.AppendLine($"    public sealed class {c.Name}");
            sb.AppendLine("    {");

            foreach (var f in c.Fields)
            {
                var csType = TableTypeMapper.ToCSharp(f.Type);
                var propName = ToPascalCase(f.Name);
                var defaultValue = GetDefaultValue(csType, f.Optional);

                if (f.Optional)
                {
                    sb.AppendLine($"        public {csType}? {propName} {{ get; set; }}");
                }
                else if (!string.IsNullOrEmpty(defaultValue))
                {
                    sb.AppendLine($"        public {csType} {propName} {{ get; set; }} = {defaultValue};");
                }
                else
                {
                    sb.AppendLine($"        public {csType} {propName} {{ get; set; }}");
                }
            }

            sb.AppendLine("    }");
        }

        private static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return char.ToUpper(input[0]) + (input.Length > 1 ? input[1..] : "");
        }

        private static string GetDefaultValue(string csType, bool optional)
        {
            if (optional) return "";
            if (csType == "string") return "\"\"";
            if (csType.EndsWith("[]")) return $"System.Array.Empty<{csType[..^2]}>()";
            return "";
        }
    }
}
