// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using Devian.Tools.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;

namespace Devian.Tools.Generators
{

    /// <summary>
    /// Protocol Opcode 할당기
    /// 자동 opcode 할당 및 충돌 검사
    /// </summary>
    public static class OpcodeAllocator
    {
        private const int DefaultStartOpcode = 1000;

        /// <summary>
        /// Protocol에 opcode 할당
        /// </summary>
        public static void AllocateOpcodes(ProtocolSpec spec, int startOpcode = DefaultStartOpcode)
        {
            var usedOpcodes = new HashSet<int>();

            // 이미 할당된 opcode 수집
            foreach (var packet in spec.Packets)
            {
                if (packet.Opcode.HasValue)
                {
                    if (!usedOpcodes.Add(packet.Opcode.Value))
                    {
                        throw new InvalidOperationException(
                            $"Duplicate opcode {packet.Opcode.Value} in packet {packet.Name}");
                    }
                }
            }

            // 미할당 패킷에 opcode 할당
            var nextOpcode = startOpcode;
            foreach (var packet in spec.Packets)
            {
                if (!packet.Opcode.HasValue)
                {
                    while (usedOpcodes.Contains(nextOpcode))
                        nextOpcode++;

                    packet.Opcode = nextOpcode;
                    usedOpcodes.Add(nextOpcode);
                    nextOpcode++;
                }
            }
        }

        /// <summary>
        /// 여러 Protocol 간 opcode 충돌 검사
        /// </summary>
        public static List<string> CheckConflicts(IEnumerable<ProtocolSpec> specs)
        {
            var conflicts = new List<string>();
            var opcodeMap = new Dictionary<int, (string Namespace, string Packet)>();

            foreach (var spec in specs)
            {
                foreach (var packet in spec.Packets)
                {
                    if (!packet.Opcode.HasValue) continue;

                    var opcode = packet.Opcode.Value;
                    if (opcodeMap.TryGetValue(opcode, out var existing))
                    {
                        conflicts.Add(
                            $"Opcode {opcode} conflict: {existing.Namespace}.{existing.Packet} vs {spec.Namespace}.{packet.Name}");
                    }
                    else
                    {
                        opcodeMap[opcode] = (spec.Namespace, packet.Name);
                    }
                }
            }

            return conflicts;
        }

        /// <summary>
        /// Opcode manifest 생성
        /// </summary>
        public static string GenerateManifest(IEnumerable<ProtocolSpec> specs)
        {
            var manifest = new Dictionary<string, Dictionary<string, int>>();

            foreach (var spec in specs)
            {
                var packets = new Dictionary<string, int>();
                foreach (var packet in spec.Packets)
                {
                    if (packet.Opcode.HasValue)
                    {
                        packets[packet.Name] = packet.Opcode.Value;
                    }
                }
                manifest[spec.Namespace] = packets;
            }

            var options = new JsonSerializerOptions { WriteIndented = true };
            return JsonSerializer.Serialize(manifest, options);
        }
    }
}
