// <auto-generated>
// Devian Build System - Table Data Generator (NDJSON)
// </auto-generated>

using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{
    /// <summary>
    /// Table Spec → NDJSON 데이터 생성 (24-table-authoring-rules, 28-json-row-io)
    /// </summary>
    public static class TableDataGenerator
    {
        /// <summary>
        /// NDJSON 포맷으로 데이터 생성 (1 row = 1 line)
        /// </summary>
        public static string Generate(TableSpec table)
        {
            var sb = new StringBuilder();
            var options = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase
            };

            foreach (var row in table.Rows)
            {
                var json = JsonSerializer.Serialize(row, options);
                sb.AppendLine(json);
            }

            return sb.ToString().TrimEnd();
        }
    }
}
