// <auto-generated>
// Devian Build System - Type Mapper
// </auto-generated>

using System;

namespace Devian.Tools.Generators
{
    /// <summary>
    /// Protocol 타입 매퍼 (62-protocolgen-implementation)
    /// </summary>
    public static class ProtocolTypeMapper
    {
        /// <summary>
        /// Protocol IDL 타입 → C# 타입
        /// </summary>
        public static string ToCSharp(string type)
        {
            // 배열 처리
            if (type.EndsWith("[]"))
            {
                var elementType = type[..^2];
                return ToCSharp(elementType) + "[]";
            }

            // map 처리
            if (type.StartsWith("map<") && type.EndsWith(">"))
            {
                var inner = type[4..^1];
                var parts = inner.Split(',', 2);
                if (parts.Length != 2)
                    throw new NotSupportedException($"Invalid map type: {type}");

                var keyType = parts[0].Trim();
                var valueType = parts[1].Trim();

                if (keyType != "string")
                    throw new NotSupportedException($"Map key must be string: {type}");

                return $"Dictionary<string, {ToCSharp(valueType)}>";
            }

            return type switch
            {
                "string" => "string",
                "bool" => "bool",
                "int32" => "int",
                "uint32" => "uint",
                "int64" => "long",
                "uint64" => "ulong",
                "float" => "float",
                "double" => "double",
                "bytes" => "byte[]",
                _ => throw new NotSupportedException($"Unsupported protocol type: {type}")
            };
        }

        /// <summary>
        /// Protocol IDL 타입 → TypeScript 타입
        /// </summary>
        public static string ToTypeScript(string type)
        {
            // 배열 처리
            if (type.EndsWith("[]"))
            {
                var elementType = type[..^2];
                return ToTypeScript(elementType) + "[]";
            }

            // map 처리
            if (type.StartsWith("map<") && type.EndsWith(">"))
            {
                var inner = type[4..^1];
                var parts = inner.Split(',', 2);
                if (parts.Length != 2)
                    throw new NotSupportedException($"Invalid map type: {type}");

                var valueType = parts[1].Trim();
                return $"Record<string, {ToTypeScript(valueType)}>";
            }

            return type switch
            {
                "string" => "string",
                "bool" => "boolean",
                "int32" or "uint32" or "int64" or "uint64" or "float" or "double" => "number",
                "bytes" => "Uint8Array",
                _ => throw new NotSupportedException($"Unsupported protocol type: {type}")
            };
        }

        /// <summary>
        /// 참조 타입인지 확인 (C#에서 default 초기화 필요 여부)
        /// </summary>
        public static bool IsReferenceType(string csType)
        {
            return csType == "string" || csType.EndsWith("[]") || csType.StartsWith("Dictionary<");
        }
    }

    /// <summary>
    /// Table/Contract 타입 매퍼 (61-tablegen, 64-contractgen)
    /// </summary>
    public static class TableTypeMapper
    {
        /// <summary>
        /// Table 타입 → C# 타입
        /// </summary>
        public static string ToCSharp(string type)
        {
            // 배열 처리
            if (type.EndsWith("[]"))
            {
                var elementType = type[..^2];
                return ToCSharp(elementType) + "[]";
            }

            // enum 참조: enum:Name
            if (type.StartsWith("enum:"))
            {
                return type[5..]; // enum:UserType → UserType
            }

            // class 참조: class:Name
            if (type.StartsWith("class:"))
            {
                return type[6..]; // class:UserProfile → UserProfile
            }

            return type switch
            {
                "byte" => "sbyte",
                "ubyte" => "byte",
                "short" => "short",
                "ushort" => "ushort",
                "int" => "int",
                "uint" => "uint",
                "long" => "long",
                "ulong" => "ulong",
                "float" => "float",
                "string" => "string",
                _ => throw new NotSupportedException($"Unsupported table type: {type}")
            };
        }

        /// <summary>
        /// Table 타입 → TypeScript 타입
        /// </summary>
        public static string ToTypeScript(string type)
        {
            // 배열 처리
            if (type.EndsWith("[]"))
            {
                var elementType = type[..^2];
                return ToTypeScript(elementType) + "[]";
            }

            // enum 참조
            if (type.StartsWith("enum:"))
            {
                return type[5..];
            }

            // class 참조
            if (type.StartsWith("class:"))
            {
                return type[6..];
            }

            return type switch
            {
                "byte" or "ubyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong" or "float" => "number",
                "string" => "string",
                _ => throw new NotSupportedException($"Unsupported table type: {type}")
            };
        }
    }
}
