// <auto-generated>
// Devian Build System - TypeScript Contract Generator
// </auto-generated>

using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{
    /// <summary>
    /// Contract Spec → TypeScript 코드 생성 (64-contractgen-implementation)
    /// </summary>
    public static class TypeScriptContractGenerator
    {
        public static string Generate(ContractSpec spec, string domain)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Enums
            if (spec.Enums != null)
            {
                foreach (var e in spec.Enums)
                {
                    GenerateEnum(sb, e);
                    sb.AppendLine();
                }
            }

            // Classes (as interfaces)
            if (spec.Classes != null)
            {
                foreach (var c in spec.Classes)
                {
                    GenerateInterface(sb, c);
                    sb.AppendLine();
                }
            }

            return sb.ToString().TrimEnd();
        }

        private static void GenerateEnum(StringBuilder sb, EnumSpec e)
        {
            if (!string.IsNullOrEmpty(e.Doc))
            {
                sb.AppendLine($"/** {e.Doc} */");
            }
            sb.AppendLine($"export enum {e.Name} {{");

            for (int i = 0; i < e.Values.Count; i++)
            {
                var v = e.Values[i];
                var comma = i < e.Values.Count - 1 ? "," : "";
                sb.AppendLine($"  {v.Name} = {v.Value}{comma}");
            }

            sb.AppendLine("}");
        }

        private static void GenerateInterface(StringBuilder sb, ClassSpec c)
        {
            if (!string.IsNullOrEmpty(c.Doc))
            {
                sb.AppendLine($"/** {c.Doc} */");
            }
            sb.AppendLine($"export interface {c.Name} {{");

            foreach (var f in c.Fields)
            {
                var tsType = TableTypeMapper.ToTypeScript(f.Type);
                var optional = f.Optional ? "?" : "";
                sb.AppendLine($"  {f.Name}{optional}: {tsType};");
            }

            sb.AppendLine("}");
        }
    }
}
