// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{

    /// <summary>
    /// TypeScript Protocol 인터페이스 생성기
    /// </summary>
    public static class TypeScriptProtocolGenerator
    {
        /// <summary>
        /// Protocol 파일 생성
        /// </summary>
        public static string Generate(ProtocolSpec spec)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Packet interfaces
            foreach (var packet in spec.Packets)
            {
                // Opcode constant
                if (packet.Opcode.HasValue)
                {
                    sb.AppendLine($"export const {packet.Name}Opcode = {packet.Opcode.Value};");
                    sb.AppendLine();
                }

                sb.AppendLine($"/** {packet.Direction} packet */");
                sb.AppendLine($"export interface {packet.Name} {{");

                foreach (var field in packet.Fields)
                {
                    var tsType = TypeMapper.ToTypeScriptType(field.Type);
                    var propName = toCamelCase(field.Name);
                    var optional = field.Optional ? "?" : "";

                    if (!string.IsNullOrEmpty(field.Comment))
                    {
                        sb.AppendLine($"  /** {field.Comment} */");
                    }
                    sb.AppendLine($"  {propName}{optional}: {tsType};");
                }

                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString().TrimEnd();
        }

        private static string toCamelCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return char.ToLower(input[0]) + (input.Length > 1 ? input[1..] : "");
        }
    }
}
