using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{
    public static class TypeScriptProtocolGenerator
    {
        public static string Generate(ProtocolSpec spec)
        {
            var sb = new StringBuilder();
            var allocator = new OpcodeAllocator();
            
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian.Tools");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            
            foreach (var msg in spec.Messages)
            {
                allocator.Allocate(msg);
                sb.AppendLine(string.Format("export type {0} = {{", msg.Name));
                
                foreach (var field in msg.Fields)
                {
                    var tsType = TypeMapper.ToTypeScript(field.Type, false);
                    var opt = field.Optional ? "?" : "";
                    var propName = TypeMapper.ToCamelCase(field.Name);
                    sb.AppendLine(string.Format("  {0}{1}: {2};", propName, opt, tsType));
                }
                
                sb.AppendLine("};");
                sb.AppendLine();
            }
            
            var nsName = TypeMapper.ToPascalCase(spec.Namespace != null ? spec.Namespace : "Protocol");
            sb.AppendLine(string.Format("export const {0}Opcode = {{", nsName));
            
            foreach (var msg in spec.Messages)
            {
                var opcode = allocator.Get(msg.Name);
                sb.AppendLine(string.Format("  {0}: {1},", msg.Name, opcode));
            }
            
            sb.AppendLine("} as const;");
            
            return sb.ToString();
        }
    }
}
