// <auto-generated>
// DO NOT EDIT - Generated by Devian Build System
// </auto-generated>

using System;
using System.Text;
using Devian.Tools.Models;

namespace Devian.Tools.Generators
{

    /// <summary>
    /// TypeScript 테이블 Row 인터페이스 생성기
    /// </summary>
    public static class TypeScriptTableGenerator
    {
        /// <summary>
        /// Row 인터페이스 생성
        /// </summary>
        public static string Generate(TableSpec spec)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // Interface
            sb.AppendLine($"export interface {spec.RowTypeName} {{");

            foreach (var col in spec.Columns)
            {
                try
                {
                    var tsType = TypeMapper.ToTypeScriptType(col.Type);
                    var propName = toCamelCase(col.Name);

                    if (!string.IsNullOrEmpty(col.Comment))
                    {
                        sb.AppendLine($"  /** {col.Comment} */");
                    }
                    sb.AppendLine($"  {propName}: {tsType};");
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException(
                        $"[table='{spec.TableName}', column='{col.Name}', type='{col.Type}'] Type conversion failed: {ex.Message}", ex);
                }
            }

            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Table 클래스 생성 (Map 기반)
        /// </summary>
        public static string GenerateTable(TableSpec spec)
        {
            var sb = new StringBuilder();
            var pkType = TypeMapper.ToTypeScriptType(spec.PrimaryKeyTypeKey);
            var pkField = toCamelCase(spec.PrimaryKeyFieldName);

            // Header
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// DO NOT EDIT - Generated by Devian Build System");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine($"import {{ {spec.RowTypeName} }} from './{spec.RowTypeName}.g';");
            sb.AppendLine();

            // Table class
            sb.AppendLine($"export class {spec.TableName}Table {{");
            sb.AppendLine($"  private readonly _map = new Map<{pkType}, {spec.RowTypeName}>();");
            sb.AppendLine();
            sb.AppendLine($"  constructor(rows: {spec.RowTypeName}[]) {{");
            sb.AppendLine($"    for (const row of rows) {{");
            sb.AppendLine($"      this._map.set(row.{pkField}, row);");
            sb.AppendLine($"    }}");
            sb.AppendLine($"  }}");
            sb.AppendLine();
            sb.AppendLine($"  get(key: {pkType}): {spec.RowTypeName} | undefined {{");
            sb.AppendLine($"    return this._map.get(key);");
            sb.AppendLine($"  }}");
            sb.AppendLine();
            sb.AppendLine($"  getAll(): {spec.RowTypeName}[] {{");
            sb.AppendLine($"    return Array.from(this._map.values());");
            sb.AppendLine($"  }}");
            sb.AppendLine();
            sb.AppendLine($"  get count(): number {{");
            sb.AppendLine($"    return this._map.size;");
            sb.AppendLine($"  }}");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string toCamelCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return char.ToLower(input[0]) + (input.Length > 1 ? input[1..] : "");
        }
    }
}
