// <auto-generated>
// Unity UIPackage Editor - UI_CONTAINER_ID Drawer
// SSOT: skills/devian-unity/23-ui-package/40-ui-container-id/SKILL.md
// </auto-generated>

#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// UI_CONTAINER_ID용 PropertyDrawer.
    /// Select 버튼 → UIContainerIdSelector (ShowUtility).
    /// </summary>
    [CustomPropertyDrawer(typeof(UI_CONTAINER_ID))]
    public sealed class UI_CONTAINER_ID_Drawer : BaseEditorID_Drawer<UIContainerIdSelector>
    {
        protected override UIContainerIdSelector GetSelector()
        {
            var w = ScriptableObject.CreateInstance<UIContainerIdSelector>();
            w.ShowUtility();
            return w;
        }
    }
}

#endif
