// <auto-generated>
// Unity UIPackage Editor - UI_CELL_ID Drawer
// SSOT: skills/devian-unity/23-ui-package/41-ui-cell-id/SKILL.md
// </auto-generated>

#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;

namespace Devian
{
    /// <summary>
    /// UI_CELL_ID용 PropertyDrawer.
    /// Select 버튼 → UICellIdSelector (ShowUtility).
    /// </summary>
    [CustomPropertyDrawer(typeof(UI_CELL_ID))]
    public sealed class UI_CELL_ID_Drawer : BaseEditorID_Drawer<UICellIdSelector>
    {
        protected override UICellIdSelector GetSelector()
        {
            var w = ScriptableObject.CreateInstance<UICellIdSelector>();
            w.ShowUtility();
            return w;
        }
    }
}

#endif
