// <auto-generated>
// Unity Scroll - UIScrollContainer Editor
// SSOT: skills/devian-unity/23-ui-package/21-ui-scroll-system/10-ui-scroll-container/SKILL.md
// </auto-generated>

using UnityEditor;
using UnityEngine;

namespace Devian
{
    [CustomEditor(typeof(UIScrollContainer))]
    public class UIScrollContainerEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            serializedObject.Update();
            DrawDefaultInspector();

            var container = (UIScrollContainer)target;

            EditorGUILayout.Space(10);
            EditorGUILayout.LabelField("Scroll View", EditorStyles.boldLabel);

            if (!Application.isPlaying)
            {
                DrawEditModePreview(container);
                serializedObject.ApplyModifiedProperties();
                return;
            }

            serializedObject.ApplyModifiedProperties();

            bool isInit = container.IsInitialized;
            EditorGUILayout.LabelField("Initialized", isInit ? "Yes" : "No");

            if (isInit)
            {
                EditorGUILayout.LabelField("Scroll Height", container.ScrollHeight.ToString("F1"));
                EditorGUILayout.LabelField("Scroll Position", container.ScrollPosition.ToString("F1"));
                EditorGUILayout.LabelField("Max Scroll Position", container.MaxScrollPosition.ToString("F1"));
            }

            EditorGUILayout.Space(5);

            using (new EditorGUI.DisabledScope(!isInit))
            {
                EditorGUILayout.BeginHorizontal();
                if (GUILayout.Button("Clear", GUILayout.Height(30))) container.Clear();
                if (GUILayout.Button("Refresh", GUILayout.Height(30))) container.Refresh();
                if (GUILayout.Button("Rebuild", GUILayout.Height(30))) container.Rebuild();
                EditorGUILayout.EndHorizontal();
            }

            if (isInit) Repaint();
        }

        private void DrawEditModePreview(UIScrollContainer container)
        {
            EditorGUILayout.LabelField("Edit Mode Preview", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox(
                "Layout-only preview입니다.\n" +
                "Content size와 section 배치만 확인하며 pooled cell spawn은 수행하지 않습니다.",
                MessageType.Info);

            var autoPreviewProp = serializedObject.FindProperty("_editorAutoPreview");
            if (autoPreviewProp != null)
            {
                EditorGUI.BeginChangeCheck();
                EditorGUILayout.PropertyField(autoPreviewProp, new GUIContent("Auto Preview"));
                if (EditorGUI.EndChangeCheck())
                {
                    serializedObject.ApplyModifiedProperties();
                    if (container.EditorAutoPreview)
                        container.EditorRequestPreviewRebuild();
                }
            }

            EditorGUILayout.LabelField("Preview Active", container.EditorPreviewActive ? "Yes" : "No");
            if (container.EditorPreviewActive)
            {
                EditorGUILayout.LabelField("Section Count", container.EditorPreviewSectionCount.ToString());
                EditorGUILayout.LabelField("Logical Row Count", container.EditorPreviewLogicalRowCount.ToString());
                EditorGUILayout.LabelField("Content Size", container.EditorPreviewContentSize.ToString("F1"));
            }

            EditorGUILayout.Space(5);
            EditorGUILayout.BeginHorizontal();
            if (GUILayout.Button("Preview Layout", GUILayout.Height(30)))
            {
                Undo.RegisterFullObjectHierarchyUndo(container.gameObject, "UIScrollContainer Preview Layout");
                container.EditorPreviewRebuildLayout();
            }

            if (GUILayout.Button("Clear Preview", GUILayout.Height(30)))
            {
                Undo.RegisterFullObjectHierarchyUndo(container.gameObject, "UIScrollContainer Clear Preview");
                container.EditorClearPreview();
            }
            EditorGUILayout.EndHorizontal();

            if (container.EditorPreviewActive)
                Repaint();
        }
    }
}
