// <auto-generated>
// Unity UIPackage Editor - UIScrollCellIdSelector
// SSOT: skills/devian-unity/23-ui-package/21-ui-scroll-system/21-ui-scroll-cell-id/SKILL.md
// </auto-generated>

#if UNITY_EDITOR

namespace Devian
{
    /// <summary>
    /// UIScrollGridCell 프리팹 기반 ID selector.
    /// BaseEditorUIAssetIdSelector&lt;UIScrollGridCell&gt; 재활용.
    /// UISettings key: "UI_SCROLL_CELL_ID"
    /// </summary>
    public sealed class UIScrollCellIdSelector : BaseEditorUIAssetIdSelector<UIScrollGridCell>
    {
        protected override string GroupKey => "UI_SCROLL_CELL_ID";
        protected override string DisplayTypeName => "UI_SCROLL_CELL_ID";
    }
}

#endif
