// <auto-generated>
// Unity Container - UI_CONTAINER_ID
// SSOT: skills/devian-unity/23-ui-package/10-base-system/32-ui-container-id/SKILL.md
// </auto-generated>

using System;

namespace Devian
{
    /// <summary>
    /// UIBaseContainer 프리팹을 참조하기 위한 string wrapper ID.
    /// Inspector에서 UIContainerIdSelector를 통해 선택한다.
    /// </summary>
    [Serializable]
    public sealed class UI_CONTAINER_ID
    {
        public string Value;

        public bool IsValid => !string.IsNullOrEmpty(Value);

        public static implicit operator string(UI_CONTAINER_ID obj)
        {
            return obj == null ? string.Empty : (obj.Value ?? string.Empty);
        }

        public static implicit operator UI_CONTAINER_ID(string value)
        {
            return new UI_CONTAINER_ID { Value = value };
        }
    }
}
