// <auto-generated>
// Devian Unity Editor - Rect Utility
// </auto-generated>

#if UNITY_EDITOR

using UnityEngine;

namespace Devian.Unity
{
    /// <summary>
    /// Utility class for splitting Rect in Editor GUI.
    /// </summary>
    public static class EditorRectUtil
    {
        /// <summary>
        /// Split a rect into left and right parts.
        /// </summary>
        /// <param name="rect">Original rect</param>
        /// <param name="leftRatio">Ratio for left part (0.0 to 1.0)</param>
        /// <returns>Tuple of (leftRect, rightRect)</returns>
        public static (Rect left, Rect right) SplitRect(Rect rect, float leftRatio)
        {
            var leftWidth = rect.width * leftRatio;
            var left = new Rect(rect.x, rect.y, leftWidth, rect.height);
            var right = new Rect(rect.x + leftWidth, rect.y, rect.width - leftWidth, rect.height);
            return (left, right);
        }

        /// <summary>
        /// Split a rect into left and right parts with fixed right width.
        /// </summary>
        /// <param name="rect">Original rect</param>
        /// <param name="rightWidth">Fixed width for right part</param>
        /// <returns>Tuple of (leftRect, rightRect)</returns>
        public static (Rect left, Rect right) SplitRectFixedRight(Rect rect, float rightWidth)
        {
            var leftWidth = rect.width - rightWidth;
            var left = new Rect(rect.x, rect.y, leftWidth, rect.height);
            var right = new Rect(rect.x + leftWidth, rect.y, rightWidth, rect.height);
            return (left, right);
        }
    }
}

#endif
